### ISSUE TITLE
Windows: pytests recursively calls itself

### ISSUE THREAD

**Issue by Dekken** [X-DataInitiative/tick#101]
I've noticed that on occasion there are some multithreading errors on windows when running the command 

```
python setup.py pytest
```

This can cause numerous python calls to the same file, which can grind a machine to a standstill.

Temporary workaround is to use the command

```
python -m unittest discover -v . "*_test.py"
```

Which does not seem to suffer from this recursion.

**Comment by stephanegaiffas** [comment]
@Dekken : is this solved ?

**Comment by Dekken** [comment]
Not unless by magic. It's super strange. I haven't been on windows in a while but can test to see

**Comment by Dekken** [comment]
Seems this has existed [since 2010](https://bugs.python.org/issue11240)

And is not resolved.

**Comment by Mbompr** [comment]
Then workaround `python -m unittest discover -v . "*_test.py"` is a totally acceptable answer !
