### ISSUE TITLE
Experience with Anaconda - Python 3.6.2 on windows

### ISSUE THREAD

**Issue by Courvoisier13** [X-DataInitiative/tick#104]
Hi guys, here is my experience with Anaconda - Python 3.6.2 on Windws 10 / Windows 7 64 bits .
I hope it will help improve the clarity for other people.

1. Add `blas_info = {}` to `setup.py ` line 107
2. The wheels and the and dependencies are not needed (included in anaconda) but it doesn't hurt to check. 
3. SWIG: uses version > 3.07 as indicated (version 2 would not work). I used SWIG 3.0.12
    3.a. Windows 10: ADD the SWIG.exe version 3.0.7 file to the "Path" environment variable.
    3.b. Windows 7: ADD the SWIG **folder** version 3.0.7 file to the "Path" environment variable. swig.exe would not work in Windows 7
4. the command `/path/to/VS/VC/Auxiliary/Build/vcvarsall.bat amd64` is not clear. This is actually the `vcvarsall.bat` in the VS BUILD TOOLS requested above. It is located in `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build` by default.
5. There is also the two SWIG environment variables ([see](http://www.swig.org/Doc3.0/Windows.html#Windows_examples)). I didn't try without those, but it's possible it would work without.
PYTHON_INCLUDE: E:\anaconda3\include
PYTHON_LIB: E:\anaconda3\libs\python36.lib

Then the compilation should work.

**Comment by Dekken** [comment]
Hi Courvoisier13,

Thanks for the information.

1. This is already [there](https://github.com/X-DataInitiative/tick/blob/master/setup.py#L85) - what you probably experiencing is a failure to find an appropriate blas with some warnings - yes?

2. That makes sense.

3. The version of swig is a copy paste error - and yes there is no bin directory for these, rather the root install can be considered the bin directory.

4. I will add a reference to the default, however it is generally wise to avoid the default install location (in my mind) as it contains spaces which are anathema when dealing with command line tooling.

I will handle these in conjunction with https://github.com/X-DataInitiative/tick/issues/105

**Comment by Dekken** [comment]
@Mbompr  has reminded me of a problem he was having regarding blas_info, and this is possibly what is occuring for you - this doesn't happen for my windows environment so I find it a bit peculiar.

What seems to be happening is that the -D define arguments for BLAS are added to the compile commands, but no blas exists and thus the head files cannot be found.

To be investigated further.

**Comment by Courvoisier13** [comment]
Thanks for your answer. yes @Mbompr was the one who told me to add this.
I tried to do the test using `python setup.py pytest` and I get 3 failures. But I couldn't figure out exactly what were they because `python setup.py pytest > test.txt` was still giving the output in the console and not in the `test.txt` file. 
There is one saying incorrect data but the other I couldn't tell.

**Comment by Dekken** [comment]
We have an issue for these 3 failing tests on windows:

https://github.com/X-DataInitiative/tick/issues/99

I believe you have to capture std-err to grap pyunit test output

    python setup.py pytest 2> test.txt

**Comment by Courvoisier13** [comment]
I compiled on windows 7 too and updated my above comment. running `python setup.py pytest 2> test.txt` now. Will keep you posted.

**Comment by Courvoisier13** [comment]
So the test just finished. 2> worked but for some reason it would get stuck and I kept having to click "Enter" every once in a while.

I get this at the end: 

> FAILED (failures=3, errors=7) 

I haven't looked in details yet, but here is the log if it is of any interest to you.
[test_khalil.txt](https://github.com/X-DataInitiative/tick/files/1377178/test_khalil.txt)

**Comment by Dekken** [comment]
Hi Courvoisier13

regarding #5 I have not need to set any environment variables - 

.1 should be resolved by https://github.com/X-DataInitiative/tick/issues/104
