### ISSUE TITLE
Supporting sparse multidimensional Hawkes processes with multiple realizations

### ISSUE THREAD

**Issue by sharonxu** [X-DataInitiative/tick#111]
In many cases we would like to model multidimensional Hawkes processes where for some realizations, there are no events in some of the components of the Hawkes.  (When modeling people, for example - each person's sequence is a realization, but not every person has activity in each component.)  Is it possible to support this? Thanks!

**Comment by Mbompr** [comment]
Hello! 

What do you mean by supporting: would our algorithms be able to fit these realizations? I think yes, most of our algorithms can run if some components have an empty sequence in few realizations. We just didn't have this in mind while developing the library so some checks would fail. This can be easily repaired with the following patch https://gist.github.com/Mbompr/28bc56ff4b94106a645ffd06f51ace41

In this case, an empty sequence would simply be an empty numpy array and the few algorithms I have tested do work. 

However, if by sparse support you mean an optimized memory storage for these realizations, it might be more complicated.

**Comment by sharonxu** [comment]
Thanks so much Martin! That's exactly what I meant - tested out the patch on a toy dataset with a fraction of empty arrays and it works on my end too with Hawkes.EM.

It seems the real data in my case may have too many empty sequences. Strangely, the error returned relates to the end_times, which I explicitly set to be larger than the latest time stamp:
RuntimeError: Provided end_time (2000) is smaller than last time of component 2 (2.31584e+77)

Component 2 in my case is pretty well populated, with 51,000 out of 76,000 nonempty arrays. However, it seems as though the algorithm is still fitting extremely high values due to lack of data. 

Does that seem right to you? And do you have an estimate as to the fraction of empty realizations for a component, such that the Hawkes algorithms will still be able to fit? It seems as if it may be less for parametric models like Hawkes.ExpKern.

Thanks again for your help!

**Comment by Courvoisier13** [comment]
Hi, I have the a similar problem. I am using daily realization of 8 point processes like your example on the bund (plot_hawkes_finance_data.html). Some of those point processes do not fall at on certain days. I have fixed my data and set the time occurrences of the empty series to be `None` when I do not have an observation on the day guaranteeing that I have 8 numpy arrays of timestamps on every day, even when one of them is None.

I get the following error: `TypeError: object of type 'NoneType' has no len()`.

What I did was to add a `np.zeros(1)` instead of `None` and that works, but i'm not sure this is the best way.

**Comment by RenqinCai** [comment]
I also have this same question. Could anyone answer how to deal with this issue? Especially for the function "tick.inference.HawkesADM4". Thanks.

**Comment by Mbompr** [comment]
Hi, I have proposed a solution and submitted in #131. If some of you would like to have a look at it, it could help us to merge it faster. Tell me if you have any issue with it.

**Comment by Mbompr** [comment]
Any news concerning this issue? Is it solved on your side now?

**Comment by RenqinCai** [comment]
Sorry for the late response. This email is put in the Spam Box.

Yes, it works now. Thanks for your quick response. I really appreciate it.
Thanks.

---Renqin cai
