### ISSUE TITLE
Access the sample data locally

### ISSUE THREAD

**Issue by Courvoisier13** [X-DataInitiative/tick#121]
I am trying `tick` on windows 7  at work behind a firewall and would like to go through the examples on the docs first. I get an error with the last 2 lines = 

```
  File "E:\anaconda3\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)

URLError: <urlopen error [Errno 11004] getaddrinfo failed>
```
It's probably because I am behind a firewall...
It would be great if we could access the files locally, especially that I can clone the actual repo in 

> https://github.com/X-DataInitiative/tick-datasets

**Comment by Mbompr** [comment]
tick-datasets downloads are cached locally on your machine (https://github.com/X-DataInitiative/tick/blob/master/tick/dataset/download_helper.py#L79)
You can probably hack the cache by downloading the file manually and store it in the correct directory.

For example, for Hawkesbund data, you can try to download this file manually (https://github.com/X-DataInitiative/tick-datasets/blob/master/hawkes/bund/bund.npz)
and store it in $HOME/tick_datasets/hawkes/bund

**Comment by Courvoisier13** [comment]
excellent. I cloned the whole library, so I can just copy that.

I am trying something else. The actual function `fetch_hawkes_bund_data()` has `dataset = 'hawkes/bund/bund.npz'` hardcoded. I can just change that.

**Comment by Mbompr** [comment]
Yes but then it is given to `fetch_tick_dataset` which will look at `$HOME/tick_datasets/hawkes/bund/bund.npz`
(https://github.com/X-DataInitiative/tick/blob/master/tick/dataset/fetch_hawkes_data.py#L24)

**Comment by Courvoisier13** [comment]
Got it. I read `def fetch_tick_dataset(dataset_path, data_home=None, verbose=True)`. when the data is local it does not copy to the `$HOME/tick_datasets/` folder which is cool.  My preference is to overwrite ` `fetch_hawkes_bund_data` and add the local path. It's just easier and I don't write anything to my user profile (writing to the user profile is not a good idea in general and we have limited space on it here).

**Comment by Mbompr** [comment]
It makes sense indeed. If you want to avoid overriding anything you can use TICK_DATASETS environment variable. It's a bit hidden in the doc but it will store and load your dataset from `$TICK_DATASETS/tick_datasets/hawkes/bund/bund.npz` instead of `$HOME/tick_datasets/hawkes/bund/bund.npz`
(cf https://github.com/X-DataInitiative/tick/blob/master/tick/dataset/download_helper.py#L158)

**Comment by Courvoisier13** [comment]
sweet. thanks!
