### ISSUE TITLE
forums? also, how to convert to .npy format?

### ISSUE THREAD

**Issue by crowlogic** [X-DataInitiative/tick#13]
Does there exist forums for general  discussion of this project?
 I've developed a hawkes process library in Java/C/C++ and would like to convert my custom data formats to the .npy format and it seems like Issues are not the proper place for this type of question. It seems I would write some code to load the custom format and use the save function in numpy https://docs.scipy.org/doc/numpy/reference/routines.io.html to put them in the .npy format . I have several terrabytes of data.. hopefully the format is efficient. 
.. my main question is, after converting to the .npy format, what would the code look like to just load this data set and implement the method of moments parameter estimator for the Hawkes sum of exponentials powerlaw approximation kernel? Ive implemented this with maximum-likelihood but found the runtime to be exceedingly slow .. I need to use the parametric kernel because I want to test a method of prediction based on inverting the closed form of the compensator .. I discussed this in a paper published at  section 1.3.4 of http://vixra.org/pdf/1211.0094v8.pdf   . when P=1 the inverse has a closed-form.. I thought the predictions of the various times of next points of buy and sell types might be used for a short-term stock buy/sell signal and wanted to do some research with the idea. Also, if anyone has any idea on the closed-form expression for P>1 which probably exists.. it would be interesting

**Comment by achab** [comment]
Hi,

No, there is no forum yet.
The method to infer the parameters of kernels written as sum of exponential is `HawkesSumExpKern`. You can find an example [here](https://x-datainitiative.github.io/tick/auto_examples/inference/plot_hawkes_sum_exp_kernels.html).
You're prediction approach is interesting, I don't know if the generalization to $p>1$ is easy though.

**Comment by crowlogic** [comment]
If github doesn't have forums, http://freeforums.org/ might be easy enough to use. That example looks straight-forward enough to start experimenting with. Thanks for the comments, it's probably not that easy to find an expression in terms of Lambert W but writing an iterative function which converges to the "next point" could probably be done in the same way that Lambert W is defined in terms of the fixed-point of a function.  I was hoping to be able to spend time working on this problem as part of a job, but my boss at my last employer was scared of mathematics and his boss was scared of programming AND math, but was really good at claiming to "run a major operation". That's wall street cults for ya.

A question about HawkesSumExpKern , does it do ML fitting or method of moments? I suspect that in order to use this prediction method in anything close to "real time" would require an adaptive method of moments that would update the existing data as new data is appended.

**Comment by Mbompr** [comment]
We are afraid that using too many different communication tools might get us lost and won't help people to search for old issues. At the moment we stick with Github issues for questions and [gitter](https://gitter.im/xdata-tick) for live chat.

About HawkesSumExpKern, parameters are minimized using least squares loss as described in the underlying [model](https://x-datainitiative.github.io/tick/modules/generated/tick.optim.model.ModelHawkesFixedSumExpKernLeastSq.html). This model also has an `incremental_fit` method that might be used to feed the model with *independent* realization sequentially. This is interesting if the whole data does not fit in memory as it updates precomputed weights progressively. This method is not available in the learner (yet?) as a learner is just a simplified wrapper. If you would like to use this method you should use the [optim module](https://x-datainitiative.github.io/tick/modules/optim.html).

In this case, lines:
```python
learner = HawkesSumExpKern(decays, penalty='elasticnet',
                           elastic_net_ratio=0.8)
learner.fit(multi.timestamps)
```

would be changed to
```python
model = ModelHawkesFixedSumExpKernLeastSq(decays)
for timestamps in multi.timestamps:
    model.incremental_fit(timestamps)

prox = ProxElasticNet(1e-3, 0.8)
solver = AGD()
solver.set_model(model)
solver.set_prox(prox)
start_coeffs = np.ones(model.n_coeffs)
solver.solve(start_coeffs)
```

**Comment by crowlogic** [comment]
Interesting, thanks for that. I'm finding it very hard to work with Python though, it would have been better to implement this project in Java for instance, but I digress, it is nice work.
