### ISSUE TITLE
Displayed code different from file

### ISSUE THREAD

**Issue by bsouhaib** [X-DataInitiative/tick#130]
The following code does not run properly: https://x-datainitiative.github.io/tick/auto_examples/plot/plot_hawkes_matrix_exp_kernels.html

Also, the displayed code is different from the code in the file. The error is due to a missing import.

Thanks.
Souhaib.

**Comment by Mbompr** [comment]
Thanks for reporting, indeed `from tick.plot import plot_hawkes_kernels` is missing at the beginning of the file. I'll try to figure out why.
