### ISSUE TITLE
Link out to referenced research

### ISSUE THREAD

**Issue by jdcc** [X-DataInitiative/tick#132]
@Mbompr You wrote in the README:
"Analyze the propagation of information in social media. Thanks to a dataset collected during 2017's presidential French election campaign on Twitter, tick is used to recover, for each topic, the network across which information spreads inside the political sphere."

This is super interesting, and very relevant to research I (and lots of other folks) are working on. Any chance we can get a link added to the README that points to said analysis?

**Comment by Mbompr** [comment]
Hi @jdcc, sadly this work is not finished and nothing has been published yet. It is rather in the readme to tell what kind of problematic tick can deal with.
I will reach you as soon as it gets published.
