### ISSUE TITLE
non-zeros coefficients abnormally low when fitting a Cox model with lasso

### ISSUE THREAD

**Issue by SimonBussy** [X-DataInitiative/tick#148]
import numpy as np
from tick.simulation import SimuCoxReg
from tick.inference import CoxRegression

n_samples = 500
weights = np.random.normal(size=50)

seed = 123
simu = SimuCoxReg(weights, n_samples=n_samples, seed=123, verbose=False)
X, Y, delta = simu.simulate()

solver = 'agd'
learner = CoxRegression(penalty='l1', tol=1e-5, C=10,
                        solver=solver, verbose=False, 
                        max_iter=100)

learner.fit(X, Y, delta)
learner.coeffs

**Comment by Mbompr** [comment]
Quick fix, this is due to the line search that is failing. You can see easily what is going on with `verbose=True` and see that only one iteration is performed with a very little step.
Learners do not let you deactivate line search easily though so you can use this little hack
```
import numpy as np
from tick.simulation import SimuCoxReg
from tick.inference import CoxRegression

n_samples = 500
weights = np.random.normal(size=50)

seed = 123
simu = SimuCoxReg(weights, n_samples=n_samples, seed=123, verbose=False)
X, Y, delta = simu.simulate()

solver = 'agd'
learner = CoxRegression(penalty='l1', tol=1e-10, C=10,
                        solver=solver, verbose=True,
                        max_iter=100, print_every=10, step=0.3)

learner._solver_obj.linesearch = False

learner.fit(X, Y, delta)
print(learner.coeffs)
```

**Comment by stephanegaiffas** [comment]
In any case this is annoying, we should use a better solver for CoxRegression IMO... several strategies, easiest to hardest (none of them being really hard) :

* change default parameters of CoxRegression to correct this kind of problems
* allow to remove linesearch from learners
* add Barzilai  for GD and AGD
* Compute lip constants for ModelCoxParlialRegresssion and use them
* Add a coordinate gradient descent solver, add relevant methods il the Cox model  and use it for CoxRegression
