### ISSUE TITLE
Weird (somewhat scary) failing unittest on last Mac OS (again)

### ISSUE THREAD

**Issue by stephanegaiffas** [X-DataInitiative/tick#166]
Here is the log : 

FAIL: test_s_sparse_array2d_memory_leaks (tick.array_test.tests.array_memory_test.Test)
...Test brute force method in order to see if we have a memory leak
----------------------------------------------------------------------

Traceback (most recent call last):
  File "/Users/stephane.gaiffas/Code/tick/tick/array_test/tests/array_memory_test.py", line 257, in test_s_sparse_array2d_memory_leaks
    delta=1.1 * bytes_size)
AssertionError: 217579520 != 216944640 within 536808.8 delta

----------------------------------------------------------------------

**Comment by Dekken** [comment]
has this been seen again?
