### ISSUE TITLE
Weird bug with import from tick.plot ? 

### ISSUE THREAD

**Issue by stephanegaiffas** [X-DataInitiative/tick#172]
I was not able to reproduce it on my laptop, but Agathe saw the following problem.
Any ideas ?

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2566533758e2> in <module>()
----> 1 from tick.plot import plot_history

/Users/agatheguilloux/anaconda/lib/python3.5/site-packages/tick/plot/__init__.py in <module>()
      8     plot_basis_kernels, plot_hawkes_baseline_and_kernels
      9 from .plot_timefunction import plot_timefunction
---> 10 from .plot_point_processes import plot_point_process
     11 
     12 

/Users/agatheguilloux/anaconda/lib/python3.5/site-packages/tick/plot/plot_point_processes.py in <module>()
      4 import numpy as np
      5 
----> 6 from tick.hawkes.simulation.base import SimuPointProcess
      7 
      8 

/Users/agatheguilloux/anaconda/lib/python3.5/site-packages/tick/hawkes/__init__.py in <module>()
     11     HawkesKernelSumExp, HawkesKernelTimeFunc
     12 )
---> 13 from .inference import (
     14     HawkesADM4, HawkesExpKern, HawkesSumExpKern, HawkesBasisKernels,
     15     HawkesConditionalLaw, HawkesEM, HawkesSumGaussians, HawkesCumulantMatching

/Users/agatheguilloux/anaconda/lib/python3.5/site-packages/tick/hawkes/inference/__init__.py in <module>()
      1 # License: BSD 3 clause
      2 
----> 3 from .hawkes_adm4 import HawkesADM4
      4 from .hawkes_basis_kernels import HawkesBasisKernels
      5 from .hawkes_conditional_law import HawkesConditionalLaw

/Users/agatheguilloux/anaconda/lib/python3.5/site-packages/tick/hawkes/inference/hawkes_adm4.py in <module>()
      4 
      5 from tick.hawkes import ModelHawkesExpKernLogLik, SimuHawkesExpKernels
----> 6 from tick.hawkes.inference.base import LearnerHawkesNoParam
      7 from tick.hawkes.inference.build.hawkes_inference import (
      8     HawkesADM4 as _HawkesADM4

/Users/agatheguilloux/anaconda/lib/python3.5/site-packages/tick/hawkes/inference/base/__init__.py in <module>()
      3 
      4 from .learner_hawkes_noparam import LearnerHawkesNoParam
----> 5 from .learner_hawkes_param import LearnerHawkesParametric

/Users/agatheguilloux/anaconda/lib/python3.5/site-packages/tick/hawkes/inference/base/learner_hawkes_param.py in <module>()
      9 from tick.base_model import ModelLipschitz
     10 from tick.hawkes import SimuHawkes
---> 11 from tick.plot import plot_point_process
     12 from tick.prox import ProxElasticNet, ProxL1, ProxL2Sq, ProxPositive
     13 from tick.solver import AGD, GD, SGD, SVRG, BFGS

ImportError: cannot import name 'plot_point_process'

**Comment by Mbompr** [comment]
Looks like a circular dependency but I don't think
`SimuPointProcess` is used no maybe can we just remove line
`from tick.hawkes.simulation.base import SimuPointProcess` ?

**Comment by stephanegaiffas** [comment]
Alright, I'll see if this removes the bug
