### ISSUE TITLE
Failed to import modules like hawkes, linear model within tick 

### ISSUE THREAD

**Issue by UAQureshi** [X-DataInitiative/tick#182]
Hi there,
I have successfully installed all the dependencies and the library itself. In python I can only import tick and from tick the base_model. I am unable to import any other module. 
Any help in this regard will be appreciated:
Thank you very much.
Below is the error:

`from tick import hawkes`

> ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\tick\hawkes\model\build\hawkes_model.py in swig_import_helper()
     13         try:
---> 14             return importlib.import_module(mname)
     15         except ImportError:

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\importlib\_bootstrap.py in _load_unlocked(spec)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\importlib\_bootstrap.py in module_from_spec(spec)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\importlib\_bootstrap_external.py in create_module(self, spec)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-3f9064cdd63d> in <module>()
      3 from tick import base_model
      4 
----> 5 from tick import hawkes

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\tick\hawkes\__init__.py in <module>()
      1 # License: BSD 3 clause
      2 
----> 3 from .model import (
      4     ModelHawkesExpKernLogLik, ModelHawkesExpKernLeastSq,
      5     ModelHawkesSumExpKernLogLik, ModelHawkesSumExpKernLeastSq,

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\tick\hawkes\model\__init__.py in <module>()
      1 # License: BSD 3 clause
      2 
----> 3 from .model_hawkes_expkern_leastsq import ModelHawkesExpKernLeastSq
      4 from .model_hawkes_expkern_loglik import ModelHawkesExpKernLogLik
      5 from .model_hawkes_sumexpkern_leastsq import ModelHawkesSumExpKernLeastSq

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\tick\hawkes\model\model_hawkes_expkern_leastsq.py in <module>()
      4 
      5 from tick.base_model import LOSS_AND_GRAD
----> 6 from tick.hawkes.model.build.hawkes_model import (
      7     ModelHawkesExpKernLeastSq as _ModelHawkesExpKernLeastSq
      8 )

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\tick\hawkes\model\build\hawkes_model.py in <module>()
     15         except ImportError:
     16             return importlib.import_module('_hawkes_model')
---> 17     _hawkes_model = swig_import_helper()
     18     del swig_import_helper
     19 elif _swig_python_version_info >= (2, 6, 0):

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\tick\hawkes\model\build\hawkes_model.py in swig_import_helper()
     14             return importlib.import_module(mname)
     15         except ImportError:
---> 16             return importlib.import_module('_hawkes_model')
     17     _hawkes_model = swig_import_helper()
     18     del swig_import_helper

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

ModuleNotFoundError: No module named '_hawkes_model'

>

**Comment by Dekken** [comment]
Hi there is a known problem on windows - while we have a fix it must go through testing.

Please consider using the most recent release in interim,

https://github.com/X-DataInitiative/tick/releases/tag/v0.4

**Comment by Dekken** [comment]
This should be resolved on master now - let us know if you have any problems

**Comment by akshitbansal** [comment]
How the issue was resolved? I am also facing the same errors on my machine.

**Comment by Dekken** [comment]
Hi there,

Please create a new ticket and attach the log

Thanks
