### ISSUE TITLE
Point-Process Intensity without Fitting

### ISSUE THREAD

**Issue by msealander** [X-DataInitiative/tick#211]
Hello -- I am interested in getting the Hawkes process intensity from an arbitrary sequence (I would input timestamps) and a known kernel (say, `HawkesKernelExp` with input parameters). I'm not seeing any way to do this. Is there? All of the intensity plots in the documentation examples seem to first simulate the data, fit it, and then plot both the simulated and fitted intensity. Thanks!

**Comment by Mbompr** [comment]
Hello @msealander,
Indeed there is no direct way of doing so as we always expect that these parameters will be estimated rather than arbitrarily set. Though, you can do a little _hack_ and set them manually by doing something similar to:
```python

import matplotlib.pyplot as plt
import numpy as np

from tick.hawkes import HawkesExpKern

decays = 2.

events = [
    np.array(
        [8.07, 48.41, 52.34, 52.84, 82.88, 84.03, 94.98, 95.72]),
    np.array(
        [48.39, 48.86, 61.64, 61.95, 75.91, 78.79, 84.43, 95.20])
]

t_min = 30
t_max = 100
fig, ax_list = plt.subplots(2, 1, figsize=(10, 6))
learner = HawkesExpKern(decays)
learner.fit(events)

baseline = [0.12, 0.07]
adjacency = np.array([[0.1, 0.3], [0.5, 0]])
learner._set('coeffs', np.hstack((baseline, adjacency.ravel())))

learner.plot_estimated_intensity(events,
                                 t_min=t_min, t_max=t_max,
                                 ax=ax_list)

plt.show()

```

**Comment by msealander** [comment]
Wow, great -- thank you! If you are curious about my motivation, I plan on optimizing the parameters across a large set of different time-series instances.

**Comment by msealander** [comment]
I think I found a small bug, where the last event is actually ignored. Using your example:
```
learner.estimated_intensity(events, intensity_track_step = 100.0)
([array([0.12      , 0.12      , 0.69647366, 0.43569063, 0.12086908,
         0.1938956 , 0.12000001, 0.44276667, 0.12      , 0.12189067,
         0.12016865, 0.14006868, 0.21888323, 0.12      , 0.24880728]),
  array([0.07      , 0.07      , 0.07      , 0.47656966, 0.07038587,
         0.4380214 , 0.07000003, 0.07000002, 0.07      , 0.07      ,
         0.07      , 0.17025884, 0.56437817, 0.07      , 0.71403642])],
 array([ 8.07, 48.39, 48.41, 48.86, 52.34, 52.84, 61.64, 61.95, 75.91,
        78.79, 82.88, 84.03, 84.43, 94.98, 95.2 ]))
```

`95.2` is the second the last event timestamp. It is also independent of the `intensity_track_step` and reproducible with different event series. In my own case, I am actually only interested in the intensity *at* the individual timestamps (including the last one), so I just select an arbitrarily large `intensity_track_step`. Thanks!

**Comment by Mbompr** [comment]
Thanks for the bug reporting! I will have a look. In the meantime, you can add an extra event at the very end to have the intensity of all your previous events.
