### ISSUE TITLE
Kaplan Meier estimator issue 

### ISSUE THREAD

**Issue by thomasdes** [X-DataInitiative/tick#222]
Hello,
In the Kaplan Meier estimator, the individual at risks (in the denominator) at time t in the program is np.sum(t <= timestamps) but this sum takes into account only the non censored individuals as timestamps = timestamps[event_observed == 1]. I think it should be np.sum(t <= timestamps) but with timestamps the original input of the function. The same comment is valid for the Nelson Aalen estimator. What do you think ?The end of the code could be:

    timestamps_observed = timestamps[event_observed == 1]
    unique_timestamps_observed = np.concatenate((np.zeros(1), np.unique(timestamps_observed)))

    return np.cumprod(
        np.fromiter((1.0 - np.sum(t == timestamps_observed) / np.sum(t <= timestamps)
                     for t in unique_timestamps_observed), dtype='float',    count=unique_timestamps_observed.size))

**Comment by stephanegaiffas** [comment]
Hi, thanks for catching this, you can do a pull request to correct this
Best
Stéphane

**Comment by stephanegaiffas** [comment]
Thanks again !
