### ISSUE TITLE
Update for python 3.7

### ISSUE THREAD

**Issue by Dekken** [X-DataInitiative/tick#263]
The last release was a while ago, and people are having issues with windows numpydoc stuff

we could probably issue a release soon, with or without ASAGA for python 3.6 and python 3.7 for convenience

**Comment by stephanegaiffas** [comment]
Yes indeed, a new release is long due !

**Comment by Dekken** [comment]
Travis has been moved to 3.7 
Appveyor to follow once tested

**Comment by Dekken** [comment]
Appveyor fails for 3.7 - https://ci.appveyor.com/project/Dekken/tick-cyjm4/build/0.5.487

**Comment by Dekken** [comment]
tensorflow isn't out for python 3.7 yet anyway
