### ISSUE TITLE
adjacency inference

### ISSUE THREAD

**Issue by trikiamine93** [X-DataInitiative/tick#269]
I have an issue with the meaning of the adjacency:

I followed your example to infer parameters using the likelihood estimator:
![hawkes](https://user-images.githubusercontent.com/25351112/43315900-06ad5742-9187-11e8-8e17-0aee49737ae5.PNG)

this is the content of lst_group:
![content list group](https://user-images.githubusercontent.com/25351112/43316144-c90b1608-9187-11e8-9d9c-d25759bc0340.PNG)

And what I get is this :
![hawkes_adj](https://user-images.githubusercontent.com/25351112/43315907-0cc77dce-9187-11e8-8f1d-67ec0a1123ea.PNG)

Can you help me interpret this ?
Is this wrong ?

When I used the adjacency and the basline to simulate the hawkes process I got this as error:

Simulation not launched as this hawkes process is not stable (spectral radius of 6.8). You can use force_simulation parameter if you really want to simulate it.

Thank you

**Comment by Mbompr** [comment]
Hi, 
First, I think that the solver has not converged. The starting point is by default a vector full of ones and it probably did not move very far from this starting point. Try using `"agd"` solver and tune the `step`.
Then, you learner is supposed to be fit on series of events with distinct timestamps. so you should remove all timestamps that are appearing multiple times.
I hope it will help.

**Comment by trikiamine93** [comment]
thank you for the response, it really helped me.

though, the likelihood gofit did not work for me, but the least-squares get the job done !

another thing, is how to choose the value of decay ?
thank you

**Comment by Mbompr** [comment]
Indeed, the least-squares loss is easier to optimize.
You can compare your loss for several values of decays and choose the decays that gives the smallest loss.
Also, if you want to use multiple decays at once you can use `HawkesSumExpKern`.
