### ISSUE TITLE
Requirement of modification in likelihood function

### ISSUE THREAD

**Issue by indianauthority97** [X-DataInitiative/tick#272]
Tick is an excellent library. However, I need to make some modification to the likelihood expression of `HawkesExpKern` so that I can modify the dimensions of `alpha` or `adjacency` matrix. I also need to get the `score` function to reflect this change for calculating the likelihood. Can it be done? If so, please direct me towards the source files where I can make the necessary changes. 

Any help would be greatly appreciated! Thanks a lot.

**Comment by Mbompr** [comment]
Hi @indianauthority97,
Thanks for this interesting question. I think we have done something similar while introducing the [sum of exponential kernels](https://x-datainitiative.github.io/tick/modules/generated/tick.hawkes.HawkesSumExpKern.html#tick.hawkes.HawkesSumExpKern). It is not super easy at it involves to modify C++ files but the additions should be quite similar.

In C++, both [`ModelHawkesExpKernLogLikSingle`](https://github.com/X-DataInitiative/tick/blob/master/lib/cpp/hawkes/model/model_hawkes_expkern_loglik_single.cpp) and [`ModelHawkesSumExpKernLogLikSingle`](https://github.com/X-DataInitiative/tick/blob/master/lib/cpp/hawkes/model/model_hawkes_sumexpkern_loglik_single.cpp) inherit from a base class [`ModelHawkesLogLikSingle`](https://github.com/X-DataInitiative/tick/blob/master/lib/cpp/hawkes/model/base/model_hawkes_loglik_single.cpp). `ModelHawkesLogLikSingle` expect them to compute weights such that the log likelihood can be expressed in the following form
![screenshot 2018-08-23 09 36 16](https://user-images.githubusercontent.com/1908833/44511799-ecb0c080-a6b8-11e8-9bd0-ea934cd88085.png)
This is what we do in [`ModelHawkesSumExpKernLogLikSingle`](https://github.com/X-DataInitiative/tick/blob/master/lib/cpp/hawkes/model/model_hawkes_sumexpkern_loglik_single.cpp) and probably what you will need to do for your specific case. Note that if the dimension of the `alpha` is different in your case, you can handle it with `get_alpha_i_first_index` and `get_alpha_i_last_index`.

Finally, once the weights are computed, you just need to add some cosmetics to make it available through Python (see [`model_hawkes_sumexpkern_loglik.py`](https://github.com/X-DataInitiative/tick/blob/master/tick/hawkes/model/model_hawkes_sumexpkern_loglik.py) and [`model_hawkes_sumexpkern_loglik.i`](https://github.com/X-DataInitiative/tick/blob/master/lib/swig/hawkes/model/list_of_realizations/model_hawkes_sumexpkern_loglik.i)).

Tell us if you have more questions. Can you tell us a bit more on your kernels?

**Comment by Mbompr** [comment]
>Another requirement I have is to be able to pass the alpha i,j's from the API call so as to fix them in the likelihood function on the go (instead of estimating both alpha and mu_i simultaneously)

No sadly you cannot fix some parameters with the current implementation.

>Also, can you elaborate a little on the significance of each term in your likelihood function?

g and G and are weights that allow much faster computations for Hawkes processes with log likelihood. Their definition are
<img width="443" alt="screenshot 2018-08-30 13 10 28" src="https://user-images.githubusercontent.com/1908833/44848230-3c156480-ac56-11e8-9bfc-18135e6ab08f.png">

> My requirement is to build a time sequence classifier using a likelihood function similar to that mentioned in https://people.eng.unimelb.edu.au/tcohn/papers/lukasik16acl.pdf

It is feasible but not straight forward. Which algorothm would you like to start from? HP Approx or HP grad? 
HP Approx uses use a very different technique to maximize the likelihood, maybe will it be easier to implement starting from [`HawkesADM4`](https://github.com/X-DataInitiative/tick/blob/master/lib/cpp/hawkes/inference/hawkes_adm4.cpp).
HP grad is closer from what we are doing but probably harder to implement and barely detailed in the paper.
