### ISSUE TITLE
Problem with plot module

### ISSUE THREAD

**Issue by aguilloux** [X-DataInitiative/tick#289]
Hi !
here is the issue.
Best
Agathe

In [1]: from tick import plot
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-db9a3379820b> in <module>()
----> 1 from tick import plot

~/anaconda3/lib/python3.6/site-packages/tick/plot/__init__.py in <module>()
      8    plot_basis_kernels, plot_hawkes_baseline_and_kernels
      9 from .plot_timefunction import plot_timefunction
---> 10 from .plot_point_processes import plot_point_process
     11 
     12 

~/anaconda3/lib/python3.6/site-packages/tick/plot/plot_point_processes.py in <module>()
      4 import numpy as np
      5 
----> 6 from tick.hawkes.simulation.base import SimuPointProcess
      7 
      8 

~/anaconda3/lib/python3.6/site-packages/tick/hawkes/__init__.py in <module>()
     11     HawkesKernelSumExp, HawkesKernelTimeFunc
     12 )
---> 13 from .inference import (
     14     HawkesADM4, HawkesExpKern, HawkesSumExpKern, HawkesBasisKernels,
     15     HawkesConditionalLaw, HawkesEM, HawkesSumGaussians, HawkesCumulantMatching

~/anaconda3/lib/python3.6/site-packages/tick/hawkes/inference/__init__.py in <module>()
      1 # License: BSD 3 clause
      2 
----> 3 from .hawkes_adm4 import HawkesADM4
      4 from .hawkes_basis_kernels import HawkesBasisKernels
      5 from .hawkes_conditional_law import HawkesConditionalLaw

~/anaconda3/lib/python3.6/site-packages/tick/hawkes/inference/hawkes_adm4.py in <module>()
      4 
      5 from tick.hawkes import ModelHawkesExpKernLogLik, SimuHawkesExpKernels
----> 6 from tick.hawkes.inference.base import LearnerHawkesNoParam
      7 from tick.hawkes.inference.build.hawkes_inference import (
      8     HawkesADM4 as _HawkesADM4

~/anaconda3/lib/python3.6/site-packages/tick/hawkes/inference/base/__init__.py in <module>()
      3 
      4 from .learner_hawkes_noparam import LearnerHawkesNoParam
----> 5 from .learner_hawkes_param import LearnerHawkesParametric

~/anaconda3/lib/python3.6/site-packages/tick/hawkes/inference/base/learner_hawkes_param.py in <module>()
      9 from tick.base_model import ModelLipschitz
     10 from tick.hawkes import SimuHawkes
---> 11 from tick.plot import plot_point_process
     12 from tick.prox import ProxElasticNet, ProxL1, ProxL2Sq, ProxPositive
     13 from tick.solver import AGD, GD, SGD, SVRG, BFGS

ImportError: cannot import name 'plot_point_process'

**Comment by Dekken** [comment]
I think this is already fixed https://github.com/X-DataInitiative/tick/issues/172
perhaps run 

```
python3 -m pip install tick --upgrade
```

I think we released the fix too

**Comment by Dekken** [comment]
Oh it would seem we released before this was fixed - 0.5.0 will have the fix - for now you can build from source if you like

**Comment by Dekken** [comment]
there's a few problems with 0.4.0 - we could release now 
@stephanegaiffas 
@Mbompr 

thoughts?

**Comment by stephanegaiffas** [comment]
Yes, we really need to realease a new version

**Comment by Dekken** [comment]
https://pypi.org/project/tick/#history 

0.4.x?
where 
1 < x < 9

**Comment by Mbompr** [comment]
It could even be 0.5.

**Comment by stephanegaiffas** [comment]
No no 0.5 !!!


Le 5 octobre 2018 à 14:10:47, Martin (notifications@github.com) a écrit:

It could even be 0.5.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/X-DataInitiative/tick/issues/289#issuecomment-427343567>,
or mute the thread

**Comment by Dekken** [comment]
this *should* be resolved now

please run ```pip install tick --upgrade```
