### ISSUE TITLE
Simulating Events using tick.hawkes

### ISSUE THREAD

**Issue by akshitbansal** [X-DataInitiative/tick#290]
I just have 1000 events at different timestamps (Unix time). I would like to know how can I fit and simulate the Hawkes process using exp. Kernel?  I am not sure how the constants are calculated.
The timestamp is the only feature I have in my dataset.

Also, how can I stimulate the events for the next 10 days?

**Comment by akshitbansal** [comment]
Also, I would like to know that If I want to stimulate events for 2 months then should still consider time in seconds for each event. Does the size of data matters in choosing the timestamp?

**Comment by akshitbansal** [comment]
learner = HawkesExpKern(decays, penalty='l1', C=10, gofit='likelihood',
verbose=True, tol=1e-11, solver='svrg', step=1e-3)
learner.fit(multi.timestamps, start=0.1)

Where alpha and mu are used?

Find max log likelihood shows error " score() missing 1 required positional argument:'self' "

How can we the values obtain after using expKernel  to as to plot with original data?

**Comment by Mbompr** [comment]
Hi, for the first question you can have a look at my response on this StackOverflow post:
https://stats.stackexchange.com/questions/366381/fit-hawkes-process-to-1d-data-using-python-package-tick

I hope this helps, tell me if you need more information. Can you then develop your next questions?
