### ISSUE TITLE
Discrepancy between in Tick/cereal/SWIG/Numpy

### ISSUE THREAD

**Issue by Dekken** [X-DataInitiative/tick#296]
When upgrading from numpy 1.14 to 1.15 - our arrays are no longer considered equal when column major - or "as fortran arrays" in numpy

It is currently uncertain where the issue lies - continuing on from https://github.com/numpy/numpy/issues/12077

@mattip

**Comment by mattip** [comment]
Could you add a summary of a test case that fails that I can run from the REPL after I install tick into a debugging environment without too much testing overhead? Something like
```
a = np.ndarray(<fill me in>)
<do something with a>
b = <something else>
assert np.all(a == b)
```

**Comment by Dekken** [comment]
is this ok?

https://github.com/Dekken/tick/blob/col_maj/tick/array/tests/col_maj_numpy.py

**Comment by mattip** [comment]
[Fails to save the file](https://gist.github.com/mattip/0c3adc22f0c3638134e086c25a873405), `Numpy array data should be contiguous (use numpy.ascontiguousarray)`. I was expecting an error when loading.

**Comment by mattip** [comment]
And I would still prefer something I can run as a 5 line script, without testing overhead. That way I can easily run it under gdb

**Comment by Dekken** [comment]
are you building from that branch?
sure let me update it

**Comment by mattip** [comment]
No I am building from master. What branch?

**Comment by Dekken** [comment]
https://github.com/Dekken/tick/blob/col_maj

**Comment by Dekken** [comment]
updated the script to be shorter
https://github.com/Dekken/tick/blob/col_maj/tick/array/tests/col_maj_numpy.py

**Comment by Dekken** [comment]
the diff of 1.14.3 / 1.15.2 for "F_CONTIG" if you're interested

```
git diff | grep F_CONTIG
-                      'F':'F', 'F_CONTIGUOUS':'F', 'FORTRAN':'F',
+                      'F': 'F', 'F_CONTIGUOUS': 'F', 'FORTRAN': 'F',
             buffer.flags |= NPY_ARRAY_F_CONTIGUOUS;
-                NULL, ip, PyArray_FLAGS(ap)&(~NPY_ARRAY_F_CONTIGUOUS), NULL);
+                PyArray_FLAGS(ap) & ~NPY_ARRAY_F_CONTIGUOUS,
-                    NPY_ARRAY_F_CONTIGUOUS);
-                NPY_ARRAY_F_CONTIGUOUS);
-    PyArray_CLEARFLAGS(ret, NPY_ARRAY_C_CONTIGUOUS | NPY_ARRAY_F_CONTIGUOUS);
-                                   PyArray_FLAGS(self)&(~NPY_ARRAY_F_CONTIGUOUS),
+            PyArray_FLAGS(self) & ~NPY_ARRAY_F_CONTIGUOUS,
          (order == NPY_FORTRANORDER && !PyArray_IS_F_CONTIGUOUS(self)))) {
-    PyArray_UpdateFlags(ret, NPY_ARRAY_C_CONTIGUOUS | NPY_ARRAY_F_CONTIGUOUS);
-                        NPY_ARRAY_C_CONTIGUOUS|NPY_ARRAY_F_CONTIGUOUS);
-                                      NPY_ARRAY_F_CONTIGUOUS)) & \
-                                              NPY_ARRAY_F_CONTIGUOUS)) \
+                    PyArray_CHKFLAGS(arr, NPY_ARRAY_F_CONTIGUOUS) \
+                                      NPY_ARRAY_F_CONTIGUOUS)) & \
+                                              NPY_ARRAY_F_CONTIGUOUS)) \
-                    PyArray_CHKFLAGS(arr, NPY_ARRAY_F_CONTIGUOUS) \
-            shape, strides = get_buffer_info(arr, ['F_CONTIGUOUS'])
+                    arr, ['F_CONTIGUOUS'])
```

**Comment by mattip** [comment]
Diving into the implementation of `tick_double_colmaj_array2d_from_file`, it is a thin wrapper over `array_from_file<SColMajArrayDouble2d>`, which itself is a wrapper around
```
template <typename A>
inline std::shared_ptr<A> array_from_file(const std::string &_file) {
  auto arr = std::make_shared<A>();
  {
    std::ifstream data(_file, std::ios::in | std::ios::binary);
    cereal::PortableBinaryInputArchive iarchive(data);
    iarchive(*arr.get());
  }
  return arr;
}
```

Still digging to understand the interplay between `iarchive` and `SColMajArrayDouble2d.get`

**Comment by Dekken** [comment]
I'm around if you have any questions

**Comment by mattip** [comment]
ahh, that seems ok, since it does not involve numpy at all. Then the result gets fed to `_XArray2d2NumpyArray` which, from the name, involves NumPy

**Comment by Dekken** [comment]
Yes indeed,
This addition was required to fix Numpy 1.14 for F_CONTIGUOUS

https://github.com/Dekken/tick/blob/col_maj/lib/swig/array/sarray_typemap_out.i#L69

**Comment by Dekken** [comment]
without these lines numpy 1.14 does not function, how can the deserialized array know it's F_CONTIGUOUS from a serialization that does not include that information?

**Comment by mattip** [comment]
Your are correct that something must be done, but simply because you set the flags from C to F contiguouse does not make it so. The real thing that needs to be done is to use `PyArrayNew` instead of `PyArray_SimpleNewFromData` and pass the appropriate flags argument there. 

NumPy should also not allow you to change the flags as you did.

**Comment by Dekken** [comment]
Ok, I'll give PyArrayNew a shot, thanks @mattip

**Comment by Dekken** [comment]
seems resolved locally - waiting for travis

**Comment by Dekken** [comment]
resolved
