### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by Dekken** [X-DataInitiative/tick#298]
My ignorance is going to be obvious here, but this is reasonable I think!

https://github.com/X-DataInitiative/tick/blob/master/lib/cpp/linear_model/model_logreg.cpp#L117

"4" has no documentation associated - perhaps a "const_expr" value with a semantically related name could be of some use

**Comment by Dekken** [comment]
another here https://github.com/X-DataInitiative/tick/blob/master/lib/cpp/linear_model/model_linreg.cpp#L30

**Comment by Mbompr** [comment]
Hard to know what would be better. It is the formula of the least squares loss 
![image](https://user-images.githubusercontent.com/1908833/46598775-91f6eb00-cae5-11e8-9225-38247ba0f2ed.png)
For logistic regression, this is inherent to the logistic loss. With 
![image](https://user-images.githubusercontent.com/1908833/46598860-ec904700-cae5-11e8-9fd8-84a7b884be9f.png)
The lipschitz constant L such that
![image](https://user-images.githubusercontent.com/1908833/46598937-32e5a600-cae6-11e8-927c-01531f1790d2.png)
is 
![image](https://user-images.githubusercontent.com/1908833/46599000-4e50b100-cae6-11e8-9326-bc4b17f19750.png).
I'm not sure that naming these constants would help the user to understand better. Do you have any suggestion?

**Comment by Dekken** [comment]
link to a Wikipedia page above the function would be good

**Comment by Mbompr** [comment]
It's reported in our doc:  [Linreg](https://x-datainitiative.github.io/tick/modules/generated/tick.linear_model.ModelLinReg.html#tick.linear_model.ModelLinReg), [Logreg](https://x-datainitiative.github.io/tick/modules/generated/tick.linear_model.ModelLogReg.html#tick.linear_model.ModelLogReg).

**Comment by Dekken** [comment]
link that then :)
