### ISSUE TITLE
issue with build - MKL library?

### ISSUE THREAD

**Issue by andrewcz** [X-DataInitiative/tick#301]
![screenshot_2018-10-09_20-09-04](https://user-images.githubusercontent.com/2296335/46658727-18532000-cbff-11e8-9f79-5d62486dc9f8.png)

Hi all!
getting a new issue on the install?
best,
Andrew

**Comment by Dekken** [comment]
Hi @andrewcz 

is your build command *just*

```python setup.py build install``` ?

this does seem a bit strange - conda comes with MKL - could you try with 

```python setup.py build install bdist_wheel```

that should disable blas/mkl altogether

**Comment by andrewcz** [comment]
ok so trying the above command now.
looks good so far....
ᐧ

**Comment by andrewcz** [comment]
yer its a bit strange...

**Comment by andrewcz** [comment]
unless i need to update conda??

**Comment by Dekken** [comment]
Oh, I don't think conda comes with MKL headers, just the library

so if you want to compile with MKL you would have to install the development tools I guess

**Comment by timleathart** [comment]
I had this issue too. Even though I had installed MKL with conda, the build script couldn't find the headers. I ended up solving it by installing MKL separately, and then running `source /opt/intel/bin/compilervars.sh intel64`, but I'm sure there's a better way to do this!

**Comment by Dekken** [comment]
perhaps try ```MKLROOT=/opt/intel/mkl python setup.py build```

It's noted in https://github.com/X-DataInitiative/tick/blob/master/INSTALL.md

**Comment by Dekken** [comment]
I'm not sure if Arch has it in a repo, but you can get it via direct download from Intel
I think just MKL for linux is < 1GB
