### ISSUE TITLE
Does tick implement the exponential approximation to the powerlaw kernel?

### ISSUE THREAD

**Issue by crowlogic** [X-DataInitiative/tick#305]
Does tick implement the exp-powerlaw approximation as described in https://arxiv.org/abs/1302.1405 ?

Instead of the magnitudes and decays being estimated directly, they are functions of a small number of parameters and hence the solution space is of a *much lower* dimension.

I've written code in Java/C to do this and it is quite easy to implement if you already have an exponential kernel solver, but I have some friends who want to do it in Pythton . can tick do it?

the way I did it in Java, is something like this

```Java
 @Override
  public double
         α(int i)
  {
    return pow(τ * pow(m, i), -(1 + ε));
  }


  @Override
  public double
         β(int i)
  {
    return τ * pow(m, -i);
  }
```

instead of just treating alpha and beta as parameters themselves to be optimized as you would do in the standard exponential kernel

**Comment by Mbompr** [comment]
Hi @crowlogic,
Sorry for the delay,
This should not be complicated at all for the simulation. For estimation though, what goodness of fit are you using? Likelihood?
Is it a convex loss? What do you use find its optimum?

**Comment by crowlogic** [comment]
Hi @Mbompr no worries. For estimation I am using a derive-free parallelized multistart optimizer, you can find my implementation at 

https://github.com/crowlogic/stochastics/blob/1335655c095d3f46086213bf6c65379ce38e0775/src/pp/selfexciting/ExponentialSelfExcitingProcess.java#L320

the log-likelihood is not quite convex, but it has a much better shape than unconstrained alpha/beta parameter estimation.. hence, I've found that if I start 30 threads from 30 different randomly chosen points in the parameter space, that the solutions converge to a small handful of clusters.. I've found that the max likelihood estimation is not always the best, and hence I developed some some criteria to weight the candidate solutions by their moment-matching, likelihood, and Ljung-Box score and it has tending to work well.
