### ISSUE TITLE
No module named '_hawkes_model'

### ISSUE THREAD

**Issue by cnktno** [X-DataInitiative/tick#306]
Hi,
When I run the example with the bund data I get the error below. I would be glad if you could help me. Thanks in advance...

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\tick\hawkes\model\build\hawkes_model.py in swig_import_helper()
     13         try:
---> 14             return importlib.import_module(mname)
     15         except ImportError:

~\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

~\Anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\Anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\Anaconda3\lib\importlib\_bootstrap.py in module_from_spec(spec)

~\Anaconda3\lib\importlib\_bootstrap_external.py in create_module(self, spec)

~\Anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: Belirtilen modül bulunamadı.

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-52ea9f93006b> in <module>()
      2 
      3 from tick.dataset import fetch_hawkes_bund_data
----> 4 from tick.hawkes import HawkesConditionalLaw
      5 from tick.plot import plot_hawkes_kernel_norms
      6 

~\Anaconda3\lib\site-packages\tick\hawkes\__init__.py in <module>()
      1 # License: BSD 3 clause
      2 
----> 3 from .model import (
      4     ModelHawkesExpKernLogLik, ModelHawkesExpKernLeastSq,
      5     ModelHawkesSumExpKernLogLik, ModelHawkesSumExpKernLeastSq,

~\Anaconda3\lib\site-packages\tick\hawkes\model\__init__.py in <module>()
      1 # License: BSD 3 clause
      2 
----> 3 from .model_hawkes_expkern_leastsq import ModelHawkesExpKernLeastSq
      4 from .model_hawkes_expkern_loglik import ModelHawkesExpKernLogLik
      5 from .model_hawkes_sumexpkern_leastsq import ModelHawkesSumExpKernLeastSq

~\Anaconda3\lib\site-packages\tick\hawkes\model\model_hawkes_expkern_leastsq.py in <module>()
      4 
      5 from tick.base_model import LOSS_AND_GRAD
----> 6 from tick.hawkes.model.build.hawkes_model import (
      7     ModelHawkesExpKernLeastSq as _ModelHawkesExpKernLeastSq
      8 )

~\Anaconda3\lib\site-packages\tick\hawkes\model\build\hawkes_model.py in <module>()
     15         except ImportError:
     16             return importlib.import_module('_hawkes_model')
---> 17     _hawkes_model = swig_import_helper()
     18     del swig_import_helper
     19 elif _swig_python_version_info >= (2, 6, 0):

~\Anaconda3\lib\site-packages\tick\hawkes\model\build\hawkes_model.py in swig_import_helper()
     14             return importlib.import_module(mname)
     15         except ImportError:
---> 16             return importlib.import_module('_hawkes_model')
     17     _hawkes_model = swig_import_helper()
     18     del swig_import_helper

~\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

ModuleNotFoundError: No module named '_hawkes_model'

**Comment by Dekken** [comment]
I think the error might be that you're using a newer numpy than what our last pip release used

```AttributeError: module 'numpydoc' has no attribute 'docscrape'```

**Comment by cnktno** [comment]
Hi,
Thank you very much for your swift answer. I have very limited knowledge
about python. I think I solved the "docscrape" problem by changing the
base.py in the folder "base" withıut changing the version of numpy. The
error I get now is "No module named _hawkes_model". It seems to be related
with swig version. I am trying to change the version of the swig. However,
I can't install earlier versions of swig using pip or conda. By the way I
changed the version of numpy and it didn't solve the problem. I would
appreciate if I can comment on whether I am in the right direction.
Thanks again...
Best,
Cenktan




♦♣♠♥ <notifications@github.com>, 13 Eki 2018 Cmt, 23:29 tarihinde şunu
yazdı:

**Comment by Dekken** [comment]
could you give me some more information about your system please?
Operating system / version / how you installed it (compiled vs pip)  / etc

**Comment by cnktno** [comment]
My O.S. is windows 10. I use Anaconda 5.1 with python 3.6. Everything I
installed is with pip or conda. I installed tick (4.0) with pip. I was
expected to download swig. I installed it with pip too. The version of swig
is 3.0.12. I don't know whether it makes a difference.   My sincere
appreciation for your time and help...
Best...

♦♣♠♥ <notifications@github.com>, 14 Eki 2018 Paz, 18:44 tarihinde şunu
yazdı:

**Comment by Dekken** [comment]
our official pip release doesn't support windows currently, but you can try this one which should work

https://ci.appveyor.com/api/buildjobs/d5pur34pl7d2vhyw/artifacts/dist%2Ftick-0.4.0.0-cp36-cp36m-win_amd64.whl

found here https://ci.appveyor.com/project/Dekken/tick-cyjm4/builds/19397111/artifacts
