### ISSUE TITLE
How to generate data from a fitted model  

### ISSUE THREAD

**Issue by akbari59** [X-DataInitiative/tick#307]
I want to fit a hawkes process to my data and then generate samples form fitted model. Based on your comments in [this post](https://github.com/X-DataInitiative/tick/issues/179), I have implemented the following:

```python
%matplotlib inline
import matplotlib.pyplot as plt

from tick.hawkes import SimuHawkesSumExpKernels, HawkesSumExpKern
from tick.plot import plot_point_process

end_time = 300

decays = [0.1, 0.5, 1.]
baseline = [0.12, 0.07]
adjacency = [[[0, .1, .4], [.2, 0., .2]],
             [[0, 0, 0], [.6, .3, 0]]]

hawkes_exp_kernels = SimuHawkesSumExpKernels(
    adjacency=adjacency, decays=decays, baseline=baseline,
    end_time=end_time, verbose=False, seed=1039)

hawkes_exp_kernels.track_intensity(0.1)
hawkes_exp_kernels.simulate()

learner = HawkesSumExpKern(decays, penalty='elasticnet',
                           elastic_net_ratio=0.8)
learner.fit(hawkes_exp_kernels.timestamps)

t_min = 100
t_max = 400
fig, ax_list = plt.subplots(2, 1, figsize=(10, 6))
learner.plot_estimated_intensity(hawkes_exp_kernels.timestamps,
                                 t_min=t_min, t_max=t_max,
                                 ax=ax_list)

plot_point_process(hawkes_exp_kernels, plot_intensity=True,
                   t_min=t_min, t_max=t_max, ax=ax_list)

# Enhance plot
for ax in ax_list:
    # Set labels to both plots
    ax.lines[0].set_label('estimated')
    ax.lines[1].set_label('original')

    # Change original intensity style
    ax.lines[1].set_linestyle('--')
    ax.lines[1].set_alpha(0.8)

    # avoid duplication of scatter plots of events
    ax.collections[1].set_alpha(0)

    ax.legend()

plt.show()
```

However, my problem is that the data generated by learner after training period has no event. What I have done wrong? My problem is that I want to use a hold-out test set for evaluation.

**Comment by filippobarchi** [comment]
> Indeed, you are not simulating any value, but only changing the x-axis on which you are displaying the estimated intensity.
> 
> To generate events from the fitted model, you should create a `Simulation` object from it. In this specific case, you can do it the following way
> 
> ```
> simu = learner._corresponding_simu()
> 
> simu.track_intensity(0.1)
> simu.set_timestamps(hawkes_exp_kernels.timestamps, hawkes_exp_kernels.end_time)
> simu.end_time = t_max
> simu.simulate()
> 
> fig = plot_point_process(simu, plot_intensity=True, t_max=t_max, show=False)
> 
> for ax in fig.get_axes():
>     ax.axvline(hawkes_exp_kernels.end_time,
>                label='New events beyond this line', color='r')
>     ax.legend()
> 
> plt.show()
> ```

i have a question: before the red line the intensity grows after the event had happen, after the red line instead the intensity grows before the event happen, why we have that?
