### ISSUE TITLE
NotImplementedError for overloaded function 'new_HawkesADM4'.

### ISSUE THREAD

**Issue by emirceyani** [X-DataInitiative/tick#313]
Hello,

In Python3.6, I'm trying to use ADM4 algorithm for Hawkes processes using 
https://x-datainitiative.github.io/tick/modules/generated/tick.hawkes.HawkesADM4.html#tick.hawkes.HawkesADM4

However, I get the following error:
python strnn_randmat.py
/home/wisevictory/anaconda3/envs/CTRNN/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "strnn_randmat.py", line 38, in <module>
    learner = HawkesADM4(decay,lasso_nuclear_ratio=1.0)
  File "/home/wisevictory/anaconda3/envs/CTRNN/lib/python3.6/site-packages/tick/hawkes/inference/hawkes_adm4.py", line 178, in __init__
    self._learner = _HawkesADM4(decay, rho, n_threads, approx)
  File "/home/wisevictory/anaconda3/envs/CTRNN/lib/python3.6/site-packages/tick/hawkes/inference/build/hawkes_inference.py", line 678, in __init__
    this = _hawkes_inference.new_HawkesADM4(decay, rho, max_n_threads, optimization_level)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_HawkesADM4'.
  Possible C/C++ prototypes are:
    HawkesADM4::HawkesADM4(double const,double const,int const,unsigned int const)
    HawkesADM4::HawkesADM4(double const,double const,int const)
    HawkesADM4::HawkesADM4(double const,double const)

Thanks in advance

**Comment by emirceyani** [comment]
Somehow, my code doesn't produce any error but I'm curious on how this error can happen?
Here's my gist:
https://gist.github.com/emirceyani/3ea13e0b83b19621c4db8c965fca8d11

Thanks again

**Comment by Dekken** [comment]
Hi there, I think it can happen when there's a mismatch between C++ and python in SWIG
From the line numbers it seems the version may be older, but your gist works for me on master

there will be a new release in the next few days (tomorrow hopefully)

**Comment by emirceyani** [comment]
@Dekken thank you for your response
