### ISSUE TITLE
Does tick implement the non-parametric branching ratio estimator described in "Branching ratio approximation for the self-exciting Hawkes process"?

### ISSUE THREAD

**Issue by crowlogic** [X-DataInitiative/tick#314]
Does tick implement the non-parametric branching ratio estimator described in "[Branching ratio approximation for the self-exciting Hawkes process](https://arxiv.org/abs/1403.5227)"?

**Comment by Dekken** [comment]
you might have a better time with these questions over @ https://gitter.im/xdata-tick/Lobby

**Comment by Mbompr** [comment]
Hi, sadly this estimator is not implemented. If you have a working python / c++ version of it, it would be a pleasure to integrate it.

**Comment by crowlogic** [comment]
not a fan of python or really c++ for that matter
