### ISSUE TITLE
Installing errors in MacOs

### ISSUE THREAD

**Issue by dangngohai** [X-DataInitiative/tick#316]
Hello,

I ran command pip install tick on the terminal but was returned an error as in below picture:
<img width="1680" alt="screenshot 2018-12-05 at 13 49 12" src="https://user-images.githubusercontent.com/23276008/49514527-96951100-f894-11e8-883b-c707ffa93c51.png">

Can you please help me to solve this issue?

Thank you very much.

**Comment by Dekken** [comment]
hi there, it looks like it's trying to build with the Intel MKL library but can not find the header file

this can can be avoided by running the install command like this 

```
python setup.py build install bdist_wheel
```

**Comment by dangngohai** [comment]
It works wells.
Thank you very much for your help.

**Comment by dangngohai** [comment]
Hello,
Sorry for bothering you again. I follow your advice and installed tick at directory "~/tick" in my macbook. However, I could not import it to Python.
<img width="1680" alt="screenshot 2018-12-06 at 03 26 51" src="https://user-images.githubusercontent.com/23276008/49557192-2673a300-f907-11e8-9d2b-b18abd2957f9.png">

Please help me to solve this problem.

**Comment by Dekken** [comment]
hi there

you should have generated a wheel file previously, you can install that with pip so you have tick in your system via python

**Comment by Dekken** [comment]
it should be in the "dist" directory

**Comment by dangngohai** [comment]
Sorry, can you please tell me what exactly I have to do? I am completely new with python and MacOS.

**Comment by dangngohai** [comment]
I did as you said and I received something like this.
<img width="1680" alt="screenshot 2018-12-06 at 11 28 55" src="https://user-images.githubusercontent.com/23276008/49578569-5728fc00-f94a-11e8-90e6-bbcffe02146d.png">
<img width="1680" alt="screenshot 2018-12-06 at 11 29 43" src="https://user-images.githubusercontent.com/23276008/49578574-5a23ec80-f94a-11e8-9e40-23d19efb3e2f.png">

**Comment by Dekken** [comment]
sorry

that should have been

``` python3 -m pip install $(ls dist/*.whl)```

you might also need

``` python3 -m pip install -r requirements.txt```

**Comment by dangngohai** [comment]
Hello,

I tried with your advice. But it still warns an error like this:
<img width="1680" alt="screenshot 2018-12-06 at 13 33 33" src="https://user-images.githubusercontent.com/23276008/49584468-b8a59680-f95b-11e8-873b-c257765e72a6.png">

**Comment by Dekken** [comment]
it's installing it into an odd location - try this

```PYTHONPATH="/Users/haidangngo:$PYTHONPATH" python3 -c "import tick;"```

**Comment by dangngohai** [comment]
I got this after running the command.
![Uploading Screenshot 2018-12-06 at 13.39.35.png…]()

**Comment by Dekken** [comment]
can you try 

```cd ~/ && python3 -c "import tick"```

if you're in the directory ~/tick this will override the installed lib version

**Comment by dangngohai** [comment]
It does not return anything. 
<img width="1680" alt="screenshot 2018-12-06 at 13 45 16" src="https://user-images.githubusercontent.com/23276008/49584926-2c946e80-f95d-11e8-9c5c-beb64dcabc43.png">

**Comment by Dekken** [comment]
that means it's successful :)

**Comment by dangngohai** [comment]
sorry for one more silly question.
How can i install the tick package to my current working project?

**Comment by Dekken** [comment]
is pycharm using your normal python/anaconda?

you might need to set some path variables or configure pycharm

I'm sorry I don't use it that much

**Comment by dangngohai** [comment]
Yes, it does. 
Anw, thank you very much for your great help.

**Comment by Mbompr** [comment]
If you can't find where you should set this in Pycharm you can always put at the beginning of your script 

```python
import sys
sys.path = ['/Users/haidangngo'] + sys.path
```

Or, preferably, edit your `/Users/haidangngo/.bashrc` file and append at the last line `PYTHONPATH="/Users/haidangngo:$PYTHONPATH"`. Then close terminal and open a new session in which `tick` should be available.
