### ISSUE TITLE
Installation issue anaconda on mac

### ISSUE THREAD

**Issue by aciniduva** [X-DataInitiative/tick#320]
I'm trying to install tick in the base(root) environments of anaconda to use it through spyder.
The package required (numpy, numpydoc, scikit-learn, scipy, matplotlib, pandas and swig) are already installed. From the terminal I run "pip install tick" but always get a "Failed building wheel for tick" error.
What am I missing?

**Comment by Dekken** [comment]
hi there, 

can you tell me what OS and version of python?

**Comment by aciniduva** [comment]
MacOs Mojave 10.14
python 3.7

and if try to install it from git get an "image not found" error

**Comment by aciniduva** [comment]
solved by creating a new environment with python 3.5.6 if needed
