### ISSUE TITLE
2 dimensional total variance

### ISSUE THREAD

**Issue by sebconort** [X-DataInitiative/tick#330]
Hello,

I'm trying to find a trick to be able with curren tick versino to perform a 2 dimensional total variance penalisation.
But as the prox objects can only act on contiguous coeffs, I cannot do it so far. Any recommandation? Do you intend to implement a way to perform 2d TV?

Thanks

**Comment by Mbompr** [comment]
Hi @sebconort,

Can you tell us more with what you mean by 2 dimensional? Does it mean that your coefficients are somehow matrices and you want to apply this, first on the row and then on the columns (like if you were applying prox TV on an image)?
I think your custom class would do the trick, but it might be even easier with [ProxMulti](https://x-datainitiative.github.io/tick/modules/generated/tick.prox.ProxMulti.html). However, the prox objects are meant to be applied on contiguous arrays, hence I am wondering if this could work in your case.

A slow but feasible solution might look like what I have done [here](https://github.com/X-DataInitiative/tick/blob/jmlr-experiments/experiments/tested_prox.py) where I am applying prox nuclear on 2 matrices that are built from a tensor. Hence, I create the correct matrices (`_get_stacked_matrix`) - that would be the creation of your _right slices_ --then I apply each proximal operator and apply the sum of all deltas. However, we need more precision to see if that's strictly equivalent.

**Comment by sebconort** [comment]
Hi @Mbompr 

Thanks quick reply.

Indeed my coefficients are somehow matrices, and I want to apply TV1D on rows and on columns.
I though about ProxMulti, but from my understanding I am still constrained on having components of the ProxMulti act on contiguous coefficients.

I ll have a look at what you did, thanks for the idea.
I ll keep you posted today I guess on my encapsulation idea.

**Comment by Mbompr** [comment]
>I though about ProxMulti, but from my understanding I am still constrained on having components of the ProxMulti act on contiguous coefficients.

Indeed, this will not work in your case for this reason.

Good luck with your idea !

**Comment by sebconort** [comment]
Hello,

I tested my idea. It partially work.
Indeed, in the method ._call of my custom "ProxTV2d" class, when I apply ProxTV on the first dimension of my matrix, then on the second dimension, only the second dimension is properly affected, as it overwritted the results of the ProxTV on the first dimension.
I used the trick to randomly apply it on of the two dimensions, at each iteration of the solver.
I works, but "partially" because I can see that coefficients are almost never set stricly equal, I have to round them...
I think it would be nice to implement a dedicated proxy (i would like to contribute but I dont know c++...)

**Comment by stephanegaiffas** [comment]
Hey, have a look at https://github.com/albarji/proxTV, it might contain what you look for.
We don't plan on adding a ProxTV2D indeed, although it's certainly doable...
Note that the strategy might really depend on the kind of neighbourhood you want to use in the 2D total variation
Also, have a look at works by Antonin Chambolle and co-authors, who have been doing a lot of research on this topic.
Cheers
S
