### ISSUE TITLE
Weird bug at python test time for LearnerSCCS

### ISSUE THREAD

**Issue by stephanegaiffas** [X-DataInitiative/tick#334]
test_LearnerSCCS_coefficient_groups (tick.survival.tests.convolutional_sccs_test.Test) ... libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process

**Comment by Dekken** [comment]
can you provide some sample code to attempt to reproduce?

dylib is mac thing, so perhaps @MaryanMorel can try to see if he has this issue too

**Comment by stephanegaiffas** [comment]
Well, it's all in the master branch and unittest failing related to ConvSCCS (ick.survival.tests.convolutional_sccs_test.Test) which seems to fail... 
It's weird that it is not catched on MacOS builds right ?

**Comment by Dekken** [comment]
> It's weird that it is not catched on MacOS builds right ?

are you using python3.7?
does your mac still randomly crash?

**Comment by stephanegaiffas** [comment]
Yep Python 3.7 it is. My mac is not crashing following  this error.

**Comment by Dekken** [comment]
python3.7 is not built on CI

**Comment by MaryanMorel** [comment]
Do you want me to try reproducing the bug using py 3.7 or is it useless anyway?
Tried few weeks ago, was not able to build using py 3.7 envs in conda

**Comment by Dekken** [comment]
I thought you could build but were getting random segfaults

**Comment by stephanegaiffas** [comment]
It's confirmed : no such  segfault when using py36, so it's yet another py37 problem :(

**Comment by Dekken** [comment]
duplicate https://github.com/X-DataInitiative/tick/issues/263
