### ISSUE TITLE
Problems in documentation for `SimuSCCS`

### ISSUE THREAD

**Issue by razhangwei** [X-DataInitiative/tick#340]
Seems that the values for `exposure_type` have been changed to `single_exposure` and `multiple_exposure`. 

https://github.com/X-DataInitiative/tick/blob/6ad84c525c695f067e2a2c99d13e05d9e9f1a780/tick/survival/simu_sccs.py#L21-L27

https://github.com/X-DataInitiative/tick/blob/6ad84c525c695f067e2a2c99d13e05d9e9f1a780/tick/survival/simu_sccs.py#L47

**Comment by Dekken** [comment]
solved by https://github.com/X-DataInitiative/tick/pull/343
