### ISSUE TITLE
Interrupt disabled after import tick

### ISSUE THREAD

**Issue by 000Justin000** [X-DataInitiative/tick#341]
```python
import time
import tick

time.sleep(100)
```

When you run this code and hit Cirl-C, the interruption is not working. Seem that somewhere in the package the keyboard interrupt is disabled. This is really troublesome for me.

**Comment by Dekken** [comment]
try it twice

**Comment by 000Justin000** [comment]
Hello Dekken,

Thank you for your response. First I tried without importing tick:

![Screenshot from 2019-03-10 17-52-08](https://user-images.githubusercontent.com/11676894/54092009-7aa27f00-435d-11e9-9193-3d1d456b3b18.png)

The interrupt works as expected. Then I tried after importing tick:

![Screenshot from 2019-03-10 17-51-39](https://user-images.githubusercontent.com/11676894/54092021-8f7f1280-435d-11e9-8f98-dd0f52543bcd.png)

The keyboard interrupt does not work anymore. Can you reproduce the error?

Thanks,
Junteng

**Comment by Dekken** [comment]
it looks like ```time.sleep``` causes a lock, it doesn't seem to end even without Ctrl-C

**Comment by Dekken** [comment]
It the cause is a C++ signal handler that doesn't forward the interrupt and exit itself.

**Comment by Dekken** [comment]
solved by https://github.com/X-DataInitiative/tick/pull/342
