### ISSUE TITLE
Estimating value of intensity for an array of irregular times

### ISSUE THREAD

**Issue by dangngohai** [X-DataInitiative/tick#360]
In your library, I understand that it is possible to compute the value of intensity at tracked steps by: `estimated_intensity(events, intensity_track_step, end_time=None)`
However, I want to compute the estimated intensity for irregular times (the interval between two events is unequal), for instance, the intensity at recorded points in the data used to estimate fitted parameters.
Is there the code for this computation?
Thanks in advance

**Comment by Dekken** [comment]
drop on over to https://gitter.im/xdata-tick/Lobby

**Comment by Dekken** [comment]
[https://gitter.im/xdata-tick/Lobby?at=5cdc4181e7f42160fa944ae0](see)
