### ISSUE TITLE
Import error for _base_model

### ISSUE THREAD

**Issue by mvicrob** [X-DataInitiative/tick#361]
Hello,

I followed the Linux installation procedure described here: https://github.com/X-DataInitiative/tick/blob/master/INSTALL.md, on a Windows 10 WSL environement, with Python 3.7. Installation built and finished OK.

But I face an error trying to simply import a Tick module:

```Python 3.7.1 (default, Oct 22 2018, 11:21:55)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tick.plot import plot_hawkes_kernels
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tick/solver/build/solver.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: _base_model.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
```
While the file exists:

```
m@m:/c/Users/Me$ ll /usr/local/lib/python3.7/dist-packages/tick/base_model/build/
total 23728
drwxr-xr-x 1 root root      512 May 16 21:35 ./
drwxr-xr-x 1 root root      512 May 16 21:35 ../
-rw-rw-rw- 1 root root      258 May 16 21:16 __init__.py
drwxr-xr-x 1 root root      512 May 16 21:35 __pycache__/
-rwxrwxrwx 1 root root 24145648 May 16 21:21 _base_model.cpython-37m-x86_64-linux-gnu.so*
-rw-rw-rw- 1 root root    36597 May 16 21:21 base_model.py
```

Do you know if I missed someting obvious ?

**Comment by stephanegaiffas** [comment]
Use Python 3.6 instead of 3.7, we still avec issues with 3.7. Cheers

**Comment by Dekken** [comment]
WSL is not tested or supported

**Comment by Dekken** [comment]
we provide a rolling wheel for windows if you'd rather use that 

can be found @ appveyor https://ci.appveyor.com/api/buildjobs/6u7ng72ml9n0ccb8/artifacts/dist%2Ftick-0.5.0.0-cp36-cp36m-win_amd64.whl

I have discovered that it does actually work if you use an alternate build method

```
cd ~/
git clone https://github.com/Dekken/maiken --depth 10 -b master git/mkn
cd git/mkn
make nix
sudo cp mkn /usr/bin
cd ~/git
git clone https://github.com/X-DataInitiative/tick --depth 10 -b master --recursive tick
cd tick
MKN_COMPILE_THREADS=4 CXXFLAGS="-march=native" ./sh/mkn.sh
export PYTHONPATH=$PWD
python3 -c "import tick"
```

**Comment by mvicrob** [comment]
Hello everyone,

Thanks for your prompt and detailed answers. I tested the above build method with Windows 10 WSL, and Python 3.6 : it works! 

On the contrary, the same build method, with the same environment, and Python 3.7 faces the issue I initially described.

No big deal, I will use Python 3.6 for this specific project.

Thanks again.

**Comment by sumau** [comment]
Just tested with Windows 10 WSL and python 3.8, it took a really long time to build the wheel but it works :-)

**Comment by sumau** [comment]
Just tested with fresh build of Windows 10 WSL and python 3.8 which failed but succeeded with 3.6 :-)
