### ISSUE TITLE
How to get estimated values of adjacency matrix, and estimated  baseline intensities after fitting real times data

### ISSUE THREAD

**Issue by rudascience** [X-DataInitiative/tick#377]

**Comment by rudascience** [comment]
Good morning,
I am trying to fit my data with HawkesADM4, but I do not know or see which function can produce the estimated values of adjacency matrix, and estimated baseline intensities after fitting real times data. And, also how to get the intensities as well. 
Can any one please help me? I really need to finish this task soon. 
Thank you so much.
Best Regards,
Ruda

**Comment by Mbompr** [comment]
Hello, did you have a look at `plot_hawkes_kernels` or `plot_hawkes_kernel_norms` functions ?

**Comment by rudascience** [comment]
Hi Mbompr, I checked again. There are function to get  adjacency matrix, and estimated baseline intensities. But there is no function to compute the conditional intensities (lambda). What function should I look to get the conditional intensity value.  
I also have another question, which function in tick can give the prediction of conditional intensity value  on test data by using the fitted parameters from training events. 
Thanks you.
Best Regards, 
Ruda

**Comment by Mbompr** [comment]
Hello, maybe https://x-datainitiative.github.io/tick/auto_examples/plot_hawkes_estimated_intensity.html is what you are looking for ?

**Comment by rudascience** [comment]
Hello, I am facing the memory error when fitting n-dimensional hawkes processes, where n >= 40000. 
Can you please give me some suggestions to deal with very big dimension? 

I very appreciate with your help.

**Comment by Dekken** [comment]
Can you provide a small example which causes this issue for you?

**Comment by rudascience** [comment]
Hello, 
Yes. Sure. 
Even when I tried with just n=3000 (n=3k), I got this error: LinAlgError: SVD did not converge.
And, sometime I tried with n=4000 is fine.
Today, I tried with n =46k on the high performance server,  I got error:
  'init dgesdd failed init' 
Is there anyway to handle with sparse & huge estimated influential matrix?
Thank you.
