### ISSUE TITLE
"Realizations" in Hawkes process

### ISSUE THREAD

**Issue by rudascience** [X-DataInitiative/tick#387]
Good afternoon everyone! 
I am trying to understand how to use tick.hawkes.hawkesADM4 for hawkes processes (in my case, let say, I have 10 users, and I want to model each user  activity (each user might tweet/retweet at certain time) in twitter as one hawkes process, so in this case, I will have 10-dimensional hawkes process. 

Might anyone help me to understand  'events' in the fit function, please?

fit(events, end_times=None, baseline_start=None, adjacency_start=None)

I have so many confusion, for example:
1) 'list of Hawkes processes realizations': does it mean that the number of point processes, so in my case is 10 point processes. 
2) How can we calculate the condition intensity for each one dimension of hawkes process?

Can anyone provide me the materials or real example that applying hawkes processes (multivariate hawkes processes with tick library?
I very appreciate with your help.
Best Regards,

**Comment by Mbompr** [comment]
Hello @rudascience,
If you have a look at the documention of [HawkesADM4](https://x-datainitiative.github.io/tick/modules/generated/tick.hawkes.HawkesADM4.html#tick.hawkes.HawkesADM4) you will find a link to a working example at the bottom of the page. It should provide you a good idea of the input format. Don't hesitate to have a look at the other examples to find out all you can do with Hawkes objects with the tick library (such as plot the conditional intensity, the kernel shapes or the matrix of the norm of the kernels...).

**Comment by rudascience** [comment]
Hi Bacry, thank you. Yes I will look on that. 
And, I also have another question is: 
I could import and did run successfully 'tick example', but yesterday when I tried with following import:
 from tick.linear_model import LogisticRegression
from tick.dataset import fetch_tick_dataset

I got the error (on windows and both on linux): ImportError: cannot import name 'comb'
or ImportError: cannot import name 'get_config'

Can you help me how can I solve this?
Thank you.

**Comment by Mbompr** [comment]
It seems that scipy has deprecated comb import from scipy.misc. You can do `pip install -U scipy==1.2.1` to avoid this behavior.

@Dekken @MaryanMorel can you fix this ? It seems to come from `from scipy.misc import comb` in `tick/preprocessing/longitudinal_features_product.py`.

**Comment by Dekken** [comment]
it is fixed on master

**Comment by rudascience** [comment]
Hi Bacry,

The tick seems work well by now. Thank you so much for quick response.
