### ISSUE TITLE
Install tick on Mac

### ISSUE THREAD

**Issue by kakarun** [X-DataInitiative/tick#389]
Hi
I want to install through Pycharm at first, but it suggested me to execute the following in command 

pip install --user tick
 
and 

Try to run this command from the system terminal. Make sure that you use the correct version of 'pip' installed for your Python interpreter located at '/usr/local/bin/python3.7'.

But I still cannot install tick by terminal:

Collecting tick
  Using cached https://files.pythonhosted.org/packages/54/f8/03266a52ca2bf5aa2121d1d5e9dd7f43238b706500ca5b0c8abd03fff0c5/tick-0.5.0.0.tar.gz
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tick) (1.17.1)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tick) (1.3.1)
Requirement already satisfied: numpydoc in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tick) (0.9.1)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tick) (3.1.1)
Requirement already satisfied: sphinx in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tick) (2.2.0)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tick) (0.25.1)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tick) (0.21.3)
Requirement already satisfied: Jinja2>=2.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from numpydoc->tick) (2.10.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->tick) (2.4.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->tick) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->tick) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->tick) (2.8.0)
Requirement already satisfied: sphinxcontrib-jsmath in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (1.0.2)
Requirement already satisfied: requests>=2.5.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (2.22.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (0.7.12)
Requirement already satisfied: sphinxcontrib-applehelp in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (1.0.1)
Requirement already satisfied: Pygments>=2.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (2.4.2)
Requirement already satisfied: snowballstemmer>=1.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (1.9.0)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (19.1)
Requirement already satisfied: imagesize in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (1.1.0)
Requirement already satisfied: babel!=2.0,>=1.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (2.7.0)
Requirement already satisfied: sphinxcontrib-devhelp in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (1.0.1)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (40.8.0)
Requirement already satisfied: docutils>=0.12 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (0.15.2)
Requirement already satisfied: sphinxcontrib-htmlhelp in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (1.0.2)
Requirement already satisfied: sphinxcontrib-serializinghtml in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from sphinx->tick) (1.1.3)
Requirement already satisfied: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas->tick) (2019.2)
Requirement already satisfied: joblib>=0.11 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from scikit-learn->tick) (0.13.2)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Jinja2>=2.3->numpydoc->tick) (1.1.1)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cycler>=0.10->matplotlib->tick) (1.12.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->tick) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->tick) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->tick) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->tick) (2019.6.16)
Requirement already satisfied: attrs in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from packaging->sphinx->tick) (19.1.0)
Building wheels for collected packages: tick
  Building wheel for tick (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-install-u8rn2i1y/tick/setup.py'"'"'; __file__='"'"'/private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-install-u8rn2i1y/tick/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-wheel-8uyhm5_p --python-tag cp37
       cwd: /private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-install-u8rn2i1y/tick/
  Complete output (11 lines):
  /private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-install-u8rn2i1y/tick/setup.py:220: DeprecationWarning: SO is deprecated, use EXT_SUFFIX
    sysconfig.get_config_var('SO'))
  running bdist_wheel
  running build
  running build_ext
  building 'tick.array.build._array' extension
  swigging lib/swig/tick/array/array_module.i to lib/swig/tick/array/array_module_wrap.cpp
  swig -python -py3 -c++ -modern -new_repr -Ilib/swig -Ilib/include -outdir tick/array/build -DDEBUG_COSTLY_THROW -o lib/swig/tick/array/array_module_wrap.cpp lib/swig/tick/array/array_module.i
  Deprecated command line option: -modern. This option is now always on.
  Deprecated command line option: -new_repr. This option is no longer supported.
  error: command 'swig' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for tick
  Running setup.py clean for tick
Failed to build tick
Installing collected packages: tick
  Running setup.py install for tick ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-install-u8rn2i1y/tick/setup.py'"'"'; __file__='"'"'/private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-install-u8rn2i1y/tick/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-record-dczym_6i/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-install-u8rn2i1y/tick/
    Complete output (10 lines):
    /private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-install-u8rn2i1y/tick/setup.py:220: DeprecationWarning: SO is deprecated, use EXT_SUFFIX
      sysconfig.get_config_var('SO'))
    running install
    running build_ext
    building 'tick.array.build._array' extension
    swigging lib/swig/tick/array/array_module.i to lib/swig/tick/array/array_module_wrap.cpp
    swig -python -py3 -c++ -modern -new_repr -Ilib/swig -Ilib/include -outdir tick/array/build -DDEBUG_COSTLY_THROW -o lib/swig/tick/array/array_module_wrap.cpp lib/swig/tick/array/array_module.i
    Deprecated command line option: -modern. This option is now always on.
    Deprecated command line option: -new_repr. This option is no longer supported.
    error: command 'swig' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-install-u8rn2i1y/tick/setup.py'"'"'; __file__='"'"'/private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-install-u8rn2i1y/tick/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/8g/5qqdnz210659z4jdh80pv9t40000gn/T/pip-record-dczym_6i/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Thanks!

**Comment by Dekken** [comment]
hi there,

we haven't yet released a whl for python3.7, we will be doing so soon

in the meantime you can build your own wheel with the master branch which is updated for swig 4.

```
git clone https://github.com/X-DataInitiative/tick --depth 1 --recursive -b master tick
cd tick
python3 setup.py bdist_wheel
python3 -m pip install dist/*
```

that should help
