### ISSUE TITLE
[Minor Fix][download_helper.py]

### ISSUE THREAD

**Issue by sara-02** [X-DataInitiative/tick#403]
The line https://github.com/X-DataInitiative/tick/blob/6989fddb7117bdf9b7c9faa284f9d163a1bee140/tick/dataset/download_helper.py#L188 returns a KeyView which being a `set-like` object cannot be accessed directly via index.

`TypeError: 'KeysView' object does not support indexing`

A minor fix is need to change it to list/or iterator instead.
```python 
key_0  = list(dataset.keys())[0]
```

**Comment by stephanegaiffas** [comment]
Yes indeed, can you do a pull request for this ? Plus len(dataset.keys()) should be replaced by len(dataset)
Best

**Comment by sara-02** [comment]
@stephanegaiffas Sure. Is there a development branch or should I create the PR against the master?

**Comment by Dekken** [comment]
master is fine :+1:
