### ISSUE TITLE
Windows segfaulting consistently with python3.7

### ISSUE THREAD

**Issue by Dekken** [X-DataInitiative/tick#411]
Not sure what has changed, but it's pretty annoying and seeminly isolated to python3.7

I did a bit of digging and it looks like it happens in numpy (when using 1.17.2 at least)

**Comment by sara-02** [comment]
Are issues #412 and #397 also related to this?

**Comment by Dekken** [comment]
I don't believe so

**Comment by Dekken** [comment]
This seems to have resolved itself
https://github.com/X-DataInitiative/tick/pull/418
