### ISSUE TITLE
Error of SimuHawkesMulti on Windows

### ISSUE THREAD

**Issue by kakarun** [X-DataInitiative/tick#412]
Hi,

I ran the sample code as follows:

```
import numpy as np

from tick.plot import plot_hawkes_kernels
from tick.hawkes import (SimuHawkes, SimuHawkesMulti, HawkesKernelExp,
                         HawkesKernelTimeFunc, HawkesKernelPowerLaw,
                         HawkesKernel0, HawkesSumGaussians)

end_time = 1000
n_nodes = 2
n_realizations = 10
n_gaussians = 5

timestamps_list = []

kernel_timefunction = HawkesKernelTimeFunc(
    t_values=np.array([0., .7, 2.5, 3., 4.]),
    y_values=np.array([.3, .03, .03, .2, 0.]))
kernels = [[HawkesKernelExp(.2, 2.),
            HawkesKernelPowerLaw(.2, .5, 1.3)],
           [HawkesKernel0(), kernel_timefunction]]

hawkes = SimuHawkes(baseline=[.5, .2], kernels=kernels, end_time=end_time,
                    verbose=False, seed=1039)

multi = SimuHawkesMulti(hawkes, n_simulations=n_realizations)

multi.simulate()

learner = HawkesSumGaussians(n_gaussians, max_iter=10)
learner.fit(multi.timestamps)

plot_hawkes_kernels(learner, hawkes=hawkes, support=4)
```
There is an error when I execute "multi.simulate()" in Pycharm on Windows, which produces a massive traceback:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python\lib\multiprocessing\spawn.py", line 105, in spawn_main
exitcode = _main(fd)
File "D:\Python\lib\multiprocessing\spawn.py", line 114, in _main
prepare(preparation_data)
File "D:\Python\lib\multiprocessing\spawn.py", line 225, in prepare
_fixup_main_from_path(data['init_main_from_path'])
File "D:\Python\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
run_name="__mp_main__")
File "D:\Python\lib\runpy.py", line 261, in run_path
code, fname = _get_code_from_file(run_name, path_name)
File "D:\Python\lib\runpy.py", line 231, in _get_code_from_file
with open(fname, "rb") as f:
  OSError: [Errno 22] Invalid argument: 'D:\\hawkes\\<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python\lib\multiprocessing\spawn.py", line 105, in spawn_main
exitcode = _main(fd)
File "D:\Python\lib\multiprocessing\spawn.py", line 114, in _main
prepare(preparation_data)
File "D:\Python\lib\multiprocessing\spawn.py", line 225, in prepare
_fixup_main_from_path(data['init_main_from_path'])
File "D:\Python\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
run_name="__mp_main__")
........

I ran the same sample code in Pycharm on Mac and there is no problem.

Thank you!

**Comment by Dekken** [comment]
multiprocessing doesn't really work on windows.

**Comment by Dekken** [comment]
this works

```
import numpy as np

from tick.plot import plot_hawkes_kernels
from tick.hawkes import (SimuHawkes, SimuHawkesMulti, HawkesKernelExp,
                         HawkesKernelTimeFunc, HawkesKernelPowerLaw,
                         HawkesKernel0, HawkesSumGaussians)

end_time = 1000
n_nodes = 2
n_realizations = 10
n_gaussians = 5
if __name__ == '__main__':
    timestamps_list = []

    kernel_timefunction = HawkesKernelTimeFunc(
        t_values=np.array([0., .7, 2.5, 3., 4.]),
        y_values=np.array([.3, .03, .03, .2, 0.]))
    kernels = [[HawkesKernelExp(.2, 2.),
                HawkesKernelPowerLaw(.2, .5, 1.3)],
               [HawkesKernel0(), kernel_timefunction]]

    hawkes = SimuHawkes(baseline=[.5, .2], kernels=kernels, end_time=end_time,
                        verbose=False, seed=1039)

    multi = SimuHawkesMulti(hawkes, n_simulations=n_realizations)

    multi.simulate()

    learner = HawkesSumGaussians(n_gaussians, max_iter=10)
    learner.fit(multi.timestamps)

    plot_hawkes_kernels(learner, hawkes=hawkes, support=4)
```

see: https://stackoverflow.com/questions/53924018/python-multiprocessing-on-windows

**Comment by kakarun** [comment]
> this works
> 
> ```
> import numpy as np
> 
> from tick.plot import plot_hawkes_kernels
> from tick.hawkes import (SimuHawkes, SimuHawkesMulti, HawkesKernelExp,
>                          HawkesKernelTimeFunc, HawkesKernelPowerLaw,
>                          HawkesKernel0, HawkesSumGaussians)
> 
> end_time = 1000
> n_nodes = 2
> n_realizations = 10
> n_gaussians = 5
> if __name__ == '__main__':
>     timestamps_list = []
> 
>     kernel_timefunction = HawkesKernelTimeFunc(
>         t_values=np.array([0., .7, 2.5, 3., 4.]),
>         y_values=np.array([.3, .03, .03, .2, 0.]))
>     kernels = [[HawkesKernelExp(.2, 2.),
>                 HawkesKernelPowerLaw(.2, .5, 1.3)],
>                [HawkesKernel0(), kernel_timefunction]]
> 
>     hawkes = SimuHawkes(baseline=[.5, .2], kernels=kernels, end_time=end_time,
>                         verbose=False, seed=1039)
> 
>     multi = SimuHawkesMulti(hawkes, n_simulations=n_realizations)
> 
>     multi.simulate()
> 
>     learner = HawkesSumGaussians(n_gaussians, max_iter=10)
>     learner.fit(multi.timestamps)
> 
>     plot_hawkes_kernels(learner, hawkes=hawkes, support=4)
> ```
> 
> see: https://stackoverflow.com/questions/53924018/python-multiprocessing-on-windows

I use the code with "if __name__ == '__main__':" and it didn't work. It still produces a massive traceback like before.
