### ISSUE TITLE
The definition of events in LearnerHawkesParametric is not consistent

### ISSUE THREAD

**Issue by bsouhaib** [X-DataInitiative/tick#415]
In LearnerHawkesParametric, events is defined differently in fit and score methods.

Is it a list of np_array or a list of list of np_array ?

I think it is a list of list of np_array. 

Please advise.

**Comment by Mbompr** [comment]
`np.array` stands for the timestamp series, `list[np.array]` stands for several timestamp series for a multidimensional Hawkes process,  `list[list[np.array]]` stands for a multiple realizations of a multidimensional Hawkes process.
In fact both methods accept `list` of of `np.ndarray` and `list` of `list` of `np.ndarray`, and if a `list` of `np.ndarray` it will be considered as one realization of a multidimensional Hawkes process.
