### ISSUE TITLE
Is it possible to forecast intensity?

### ISSUE THREAD

**Issue by dvalentind** [X-DataInitiative/tick#417]

**Comment by dvalentind** [comment]
Hello!

Is it possible to forecast intensity using this library? If yes, can I somehow specify a starting point of the forecast? For example, I have fitted the model using HawkesKernelExp till time _t_, and want to forecast intensity starting from _t+10_?

**Comment by Mbompr** [comment]
Hi,
Does issue https://github.com/X-DataInitiative/tick/issues/307 answer your question ?

**Comment by dvalentind** [comment]
Hi, 

Sorry of the delayed response. Yes, it answers my question, that you!
On thing I would like to clarify, do I understand correctly that library uses Ogata’s thinning method to simulate new events?

Thank you!

**Comment by Mbompr** [comment]
Yes, simulation is done with Ogata's thinning algorithm (implemented here : https://github.com/X-DataInitiative/tick/blob/master/lib/cpp/hawkes/simulation/simu_point_process.cpp#L107).
Thanks !
