### ISSUE TITLE
In the learning of Hawkes process, where can I decide the begining time stamp of input history data.

### ISSUE THREAD

**Issue by DavidZhang88** [X-DataInitiative/tick#420]
For example, while calculating the log likelihood function, the beginning  and ending time-stamps of history data which is also very import,  For example. if we consider multiple event sequences ,the time stamps of the earliest events in one sequence could be set to zero,and in other sequences, the beginning time stamp may be not 0. The frame of likelihood should be:
![QQ截图20200129234655](https://user-images.githubusercontent.com/26404027/73372097-a5891f00-42f1-11ea-9340-9a3b20e29241.jpg)
Base on this view, I try to find how to input the the begining time of the history, but I failed, could your offer me some help? Thank you so much.

**Comment by DavidZhang88** [comment]
And In Hawkes process simulation, which algorithms do you adopt? such as Ogata thinning algorithm, I can't find the introduction ,could you please tell me?

**Comment by Mbompr** [comment]
Q1 : in tick, beginning and ending timestamps are the same for all sequences in one realization. It is not something we had in mind while implementing the algorithms.

Q2 : We use Ogata thinning algorithm, see https://github.com/X-DataInitiative/tick/blob/master/lib/cpp/hawkes/simulation/simu_point_process.cpp#L107 for its C++ implementation

**Comment by DavidZhang88** [comment]
Thank you very much for your generous help, it helped me a lot to understand the code.
