### ISSUE TITLE
sklearn breaking changes

### ISSUE THREAD

**Issue by Dekken** [X-DataInitiative/tick#421]
changes in sklearn version 0.22 in OneHotEncoder [breaks](https://github.com/X-DataInitiative/tick/blob/master/tick/preprocessing/features_binarizer.py#L171)

[current](https://scikit-learn.org/0.22/modules/generated/sklearn.preprocessing.OneHotEncoder.html)

vs

[older](https://scikit-learn.org/0.21/modules/generated/sklearn.preprocessing.OneHotEncoder.html)

**Comment by Dekken** [comment]
perhaps @MaryanMorel can give some suggestion

**Comment by Mbompr** [comment]
I think something can be done with `categories_` and maybe `drop_idx_`. I can't have a look right now, but if we manage to get the [test](https://github.com/X-DataInitiative/tick/blob/master/tick/preprocessing/tests/features_binarizer_test.py) pass we can be quite confident in the fix.
