### ISSUE TITLE
Issues in code

### ISSUE THREAD

**Issue by RuihuaRUAN** [X-DataInitiative/tick#423]
Hi,

There could be a little error on the **line 166** in 

[tick/tick/hawkes/simulation/base/simu_point_process.py](https://github.com/X-DataInitiative/tick/blob/master/tick/hawkes/simulation/base/simu_point_process.py) 

```
     if self.end_time is None and self.max_jumps is None:
        raise (ValueError('Either end_time or max_jumps must be set'))
                                          .............
     elif self.end_time is None and self.max_jumps is None:
        self._pp.simulate(self.end_time, self.max_jumps)
```
I think the last condition should be 
`elif self.end_time is not None and self.max_jumps is not None:`. 

Regards,
Ruihua

**Comment by Dekken** [comment]
PR welcome!

**Comment by Dekken** [comment]
https://github.com/X-DataInitiative/tick/blob/master/tick/hawkes/simulation/base/simu_point_process.py#L166
fixed
