### ISSUE TITLE
Estimation of second-order statistics conditional law g_{ij}(t) in tick 

### ISSUE THREAD

**Issue by kakarun** [X-DataInitiative/tick#433]
Hi,

How to use functions in tick to estimate the second-order statistics, i.e, conditional law g_{ij}(t)? It seems that tick.hawkes.HawkesConditionalLaw can only output the estimation of the kernels, i.e., \phi_{ij}(t).

Thanks!

**Comment by Mbompr** [comment]
Hi,

Sadly, this code was adapted from another codebase and I don't remember much about it. But maybe you could find what you are looking for in the private attributes or methods of the class, such as `hawkes._G` function ?

    def _G(self, i, j, l, t):
        """Returns the value of a claw at a point
        Used to fill V and M with 'gauss' method
        """
        if t < 0:
            warnings.warn("G(): should not be called for t < 0")
        index = self._ijl2index[i][j][l]
        return HawkesConditionalLaw._lin0(self._int_claw[index], t)

**Comment by kakarun** [comment]
> Hi,
> 
> Sadly, this code was adapted from another codebase and I don't remember much about it. But maybe you could find what you are looking for in the private attributes or methods of the class, such as `hawkes._G` function ?
> 
> ```
> def _G(self, i, j, l, t):
>     """Returns the value of a claw at a point
>     Used to fill V and M with 'gauss' method
>     """
>     if t < 0:
>         warnings.warn("G(): should not be called for t < 0")
>     index = self._ijl2index[i][j][l]
>     return HawkesConditionalLaw._lin0(self._int_claw[index], t)
> ```

Thanks for your reply!
