### ISSUE TITLE
right way to seed simulate() for reproducible results

### ISSUE THREAD

**Issue by dionman** [X-DataInitiative/tick#436]
From a bash script, I'm calling twice a python script where following line gets identically instantiated
```
hawkes_exp_kernels = SimuHawkesExpKernels(adjacency=adjacency, decays=1.,
                                          baseline=baseline, end_time=T,
                                          verbose=False, seed=np.random.seed(ID))
```
I end up getting simulations of (similar but) different length.
What's the right way to call ```hawkes_exp_kernels.simulate()``` with fixed seed in order to get reproducible simulations?

**Comment by Dekken** [comment]
I think the seed needs to be a constant.

try ```seed=1337```

**Comment by dionman** [comment]
thanks, this works
