### ISSUE TITLE
Fitting inhomogeneous Poisson via LSE

### ISSUE THREAD

**Issue by dionman** [X-DataInitiative/tick#437]
Is LSE (or MSE) fitting of an inhomogeneous Poisson process on a given events sequence supported at the moment?

**Comment by Mbompr** [comment]
Hello, 
No only Hawkes processes can be fit with this lib. What kind of loss would you like to minimize to estimate an inhomogeneous Poisson process if you make to hypothesis?

**Comment by dionman** [comment]
I was thinking about LSE.
Can you point me to the analytical expression you use to compute the least square loss in ```hawkes_expkern_leastsq```?

**Comment by Mbompr** [comment]
It is described in I.2 of https://tel.archives-ouvertes.fr/tel-02316143/document

**Comment by dionman** [comment]
thanks!
