### ISSUE TITLE
Implementation Details for Co-occurring Events in ModelHawkesSumExpKernLeastSq

### ISSUE THREAD

**Issue by yifeim** [X-DataInitiative/tick#478]
Hi,

I have a question about the implementation details for co-occurring events. Co-occurring events are quite common in practice, e.g., due to rounding of timestamps. I searched around the documentation and saw 
[ModelHawkesSumExpKernLeastSq](https://x-datainitiative.github.io/tick/modules/generated/tick.hawkes.ModelHawkesSumExpKernLeastSq.html)
to be the adopted learner for Hawkes models. The documentation says `t_k^j<t` when constructing the intensity kernels, which seems to be a natural extension of TPP in time-rounded environments. I wonder if this is actually implemented in the codes - which requires double pointers to increment time in mini-jumps, or only done for the natural order of events, presumably leaking information about same-time events. In any case, this would be good to discuss in the documentation.

Thanks.

**Comment by yifeim** [comment]
Maybe is it supported here?

https://github.com/X-DataInitiative/tick/blob/master/lib/cpp/hawkes/model/model_hawkes_expkern_leastsq_single.cpp#L186

**Comment by Bacry** [comment]
Hello,

I co-occurring events are present in your data because of rounding of 
timestamps, it means that they are artefact.
So I would not try to model them as being co-occuring.

My advice would be to add some small noise to the timestamps so that 
there are no co-occuring events any more

Emmanuel
