### ISSUE TITLE
Simulation for HawkesConditionalLaw or HawkesCumulantMatching

### ISSUE THREAD

**Issue by csaiedu** [X-DataInitiative/tick#480]
Hi
I can't seem to be able after fitting HawkesConditionalLaw or HawkesCumulantMatching to simulate using SimuHawkesMulti on the resulting process, resulting in error messages. Is that the correct way to perform a prediction using simulation for those two non parametric processes?

Thank you

**Comment by Mbompr** [comment]
Hi, 
* For HawkesConditionalLaw, you can use HawkesKernelPowerLaw (see https://x-datainitiative.github.io/tick/auto_examples/plot_hawkes_conditional_law.html)
* For HawkesCumulantMatching, the kernel is not estimated, only its norm is. Hence unless you assume any specific shape for it, you will not be able to run simulations with it.

**Comment by csaiedu** [comment]
Thanks for the explanation..

**Comment by csaiedu** [comment]
Actually for the HawkesConditionalLaw. there isn't any estimated_density() function.
Assuming I fit the kernels using a power law curve fitting strategy to find parameters as per your comments
"Otherwise you might use non parametric learners. I would suggest you to use HawkesConditionalLaw that has been specifically tested on power law kernels. Maybe can you then roughly estimate the powerlaw parameters by doing a linear regression in log-log space since \log( \phi(t)) = \log(\alpha) - \beta \log (t + \delta)log(ϕ(t))=log(α)−βlog(t+δ). Assuming \deltaδ is small, you can estimate correctly \alphaα and \betaβ for big values of tt and then estimate \deltaδ."


    hawkes = SimuHawkes(
        kernels=[[
            HawkesKernelPowerLaw(multiplier[0], cutoff, exponent, support),
            HawkesKernelPowerLaw(multiplier[1], cutoff, exponent, support)
        ], [
            HawkesKernelPowerLaw(multiplier[2], cutoff, exponent, support),
            HawkesKernelPowerLaw(multiplier[3], cutoff, exponent, support)
        ]], baseline=[0.05, 0.05], seed=382, verbose=False)

How do I use that kernel to calculate the intensity on my own timestamps, rather than simulating one. I tried using set_intensity(own_time_stamps) but can't access the calculated intensity to be able to perform predictions.

Thank you
