### ISSUE TITLE
HawkesCumulantMatching missing R

### ISSUE THREAD

**Issue by csaiedu** [X-DataInitiative/tick#481]
I am trying to retrieve the matrix of events of exogeneous origin using the attribute R, the "Estimated weight, linked to the integrals of Hawkes kernels. Use to derive adjacency and baseline defined in the attributes of the HawkesCumulantMatching" :

https://x-datainitiative.github.io/tick/modules/generated/tick.hawkes.HawkesCumulantMatching.html

But it doesn't seem to be defined

AttributeError: 'HawkesCumulantMatching' object has no attribute 'R'

```

import numpy as np
from tick.dataset import fetch_hawkes_bund_data
from tick.plot import plot_hawkes_kernel_norms
from tick.hawkes import  HawkesCumulantMamatrix tching

np.random.seed(7168)

n_nodes = 4

integration_support = 500

    
timestamps_list = fetch_hawkes_bund_data()

nphc = HawkesCumulantMatching(integration_support, cs_ratio=.01, tol=1e-10,
                              step=.5)

nphc.fit(timestamps_list)

plot_hawkes_kernel_norms(nphc,node_names=["P_u", "P_d", "T_a", "T_b"])

print(nphc.R)

reference paper https://arxiv.org/abs/1706.03411 page 3

**Comment by Mbompr** [comment]
Indeed it does not seem to be correctly exposed, have you tried 
```python
with nphc._tf_graph.as_default():
            R = nphc._tf_model_coeffs
```
inspired from the source code https://x-datainitiative.github.io/tick/_modules/tick/hawkes/inference/hawkes_cumulant_matching.html#HawkesCumulantMatching ?

**Comment by csaiedu** [comment]
Thanks for the quick reply.
Pardon my ignorance but how do I get the value of R, I don't seem to be able to use numpy() or see the coefficients, only this

<tf.Variable 'model/R:0' shape=(4, 4) dtype=float64_ref>

**Comment by Mbompr** [comment]
Hum indeed, this is only a tensorflow variable. 
To be honest I do not remember this code well. Maybe you can retrieve the R variable by spawning a new tf session, but possibly this would have been possible only during the training. In such case you should probably edit the class to get the value of R at the end of the training, before the tf session ends.

**Comment by trouleau** [comment]
Hi! If I'm not mistaken the `HawkesCumulantMatching` object has an attribute `solution` which is a numpy array that holds the solution of the optimisation. The `adjacency` attribute is actually just a property that's calling `solution` behind it: https://github.com/X-DataInitiative/tick/blob/bbc561804eb1fdcb4c71b9e3e2d83a66e7b13a48/tick/hawkes/inference/hawkes_cumulant_matching.py#L268-L270

**Comment by csaiedu** [comment]
Thank you
