### ISSUE TITLE
Derivation of least square loss for hawkes process

### ISSUE THREAD

**Issue by HaochenWang1243** [X-DataInitiative/tick#522]
Hi. I simply wondered how is the least square loss for `HawkesExpKern`
![Screenshot 2024-09-26 at 11 11 14](https://github.com/user-attachments/assets/06e89b85-10d5-4a85-8662-95dade0d523a)
derived?

**Comment by PhilipDeegan** [comment]
Hi @HaochenWang1243

You're probably more likely to get a response if you check the author on the commits that are in this file and tag that person direclty.

**Comment by Mbompr** [comment]
Hello,
Among other docuements, this is detailed in https://theses.hal.science/tel-02316143v1/document page 20.
<img width="582" alt="image" src="https://github.com/user-attachments/assets/45bd80cd-b472-4f0a-9d04-3fae06a00679">

**Comment by HaochenWang1243** [comment]
Thank you very much
