### ISSUE TITLE
Documentation website broken

### ISSUE THREAD

**Issue by jengelman** [X-DataInitiative/tick#67]
https://x-datainitiative.github.io/tick/index.html is nonfunctional, tested on multiple computers.  

The examples page has only black boxes, and the examples themselves have no images, only code:
<img width="588" alt="screen shot 2017-08-29 at 10 00 16 pm" src="https://user-images.githubusercontent.com/24788497/29853436-90c1672a-8d05-11e7-87b4-07036a5e4683.png">

The API reference looks entirely like the following:
<img width="965" alt="screen shot 2017-08-29 at 10 00 08 pm" src="https://user-images.githubusercontent.com/24788497/29853437-90c4c988-8d05-11e7-864a-f3c42866a9e1.png">

Looks like a Sphinx issue?

**Comment by Mbompr** [comment]
Hi, sorry about that, it was due to a hot fix I've done last week. It's all fixed now :).

**Comment by jengelman** [comment]
Looks good, thanks!
