### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ashishdandekar** [X-DataInitiative/tick#68]
When I try to import tick, it raises an ImportError saying "No module named '_array'!"
If I trace "tick.base.array.build._array" there indeed is not any _array module.

**Comment by Mbompr** [comment]
Hi! What platform are you installing tick on? Which installation method did you use?
If you are on OSX, which version is it?

**Comment by ashishdandekar** [comment]
Hi

My bad that I forgot to report that earlier. I am installing it on Ubuntu Ubuntu 16.04! I am installing from the source

**Comment by Mbompr** [comment]
I cannot reproduce this error with this config, did you try to run ./clean_build_test.sh from the root directory? Which Python version do you use?

**Comment by ashishdandekar** [comment]
I am using Python 3.5.2!

**Comment by Mbompr** [comment]
Alright, well I don't see any obvious issue. Did you try to run `./clean_build_test.sh` from the root directory? Did this caused the import error or did you write another script that has caused the error?

If you have written another script, which path pointing to _tick_ did you add in your PYTHONPATH? Is the folder tick/base/array/build empty there?

**Comment by ashishdandekar** [comment]
Surprisingly after running clean_build_test script, I am able to import tick without any error. But the script raised two errors. The log is given below:

```
======================================================================
FAIL: test_ModelHawkesFixedExpKernLogLik_hessian (tick.optim.model.tests.hawkes_fixed_expkern_loglik_test.Test)
...Numerical consistency check of hessian for Hawkes loglik
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ashish/Study/programs/synthetic/tick/tick/optim/model/tests/hawkes_fixed_expkern_loglik_test.py", line 183, in test_ModelHawkesFixedExpKernLogLik_hessian
    np.testing.assert_array_equal(hessian, hessian.T)
  File "/home/ashish/.virtualenvs/missions/lib/python3.5/site-packages/numpy/testing/utils.py", line 813, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/ashish/.virtualenvs/missions/lib/python3.5/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: [repr failed]
 y: [repr failed]

======================================================================
FAIL: test_ModelLinRegWithIntercepts (tick.optim.model.tests.linreg_with_intercepts_test.Test)
...Numerical consistency check of loss and gradient for Linear
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ashish/Study/programs/synthetic/tick/tick/optim/model/tests/linreg_with_intercepts_test.py", line 31, in test_ModelLinRegWithIntercepts
    self.run_test_for_glm(model, model_spars, 1e-4, 1e-4)
  File "/home/ashish/Study/programs/synthetic/tick/tick/optim/model/tests/generalized_linear_model.py", line 38, in run_test_for_glm
    delta_model_grad=delta_model_grad)
  File "/home/ashish/Study/programs/synthetic/tick/tick/optim/model/tests/generalized_linear_model.py", line 21, in _test_grad
    delta=delta_check_grad)
AssertionError: 0.38214569828563916 != 0.0 within 0.0001 delta
```

**Comment by Mbompr** [comment]
Oh good news! Concerning these two errors, it is indeed a problem in the master that surprisingly Travis did not detect. We are working on it but it should not bother you.

**Comment by mariolovric** [comment]
I have the same issue in Ubuntu, installed via pip
Where is this clean_build_test.sh stored? Cant find it.
Thanks.

**Comment by Dekken** [comment]
Hi Mario, installing via pip does not provide all the sources "clean_build_test.sh" is available in the "sh" directory of the repo

**Comment by Mbompr** [comment]
Hi @mariolovric,
I'm not sure to fully understand, how do you launch the tests if you have installed tick from pip? Is the error message exactly the same as the one provided above?

**Comment by mariolovric** [comment]
Solved it. Had to update Numpy.
Thanks
