### ISSUE TITLE
Cereal serialization of models

### ISSUE THREAD

**Issue by stephanegaiffas** [X-DataInitiative/tick#79]
Some models are not serializable; This needs to change :)

**Comment by Dekken** [comment]
I've made a start to this, just linear_model and robust so far - requires serializing all the proxes too while we're at it

just testing with SAGA so far but will add the others. 

how would you like this? in parts? one PR per module?

**Comment by Mbompr** [comment]
I guess proxs or models for example will be able to be serialized on their own. If so, yes I guess if we can have independant PR for this modules it could be cleaner :).

**Comment by Dekken** [comment]
All but survival and hawkes modules have been serialized in C++/Python

**Comment by Dekken** [comment]
https://github.com/X-DataInitiative/tick/pull/250 can probably close this too
