### ISSUE TITLE
setup.py broken

### ISSUE THREAD

**Issue by crowlogic** [X-DataInitiative/tick#9]
~/src/tick$ python setup.py 
  File "setup.py", line 87
    def __init__(self, *args, module_ref=None, **kwargs):
                                       ^
SyntaxError: invalid syntax

**Comment by vinther** [comment]
What version of Python are you using? Can you provide the output of `python -V`?

**Comment by crowlogic** [comment]
Python 2.7.13

**Comment by Mbompr** [comment]
_tick_ requires Python 3.4 or newer. Do you need help to install Python 3 alongside Python 2?

**Comment by crowlogic** [comment]
ah hah, that explains it. Thanks. I've got python 3.5 and 3.6 but 
installed via the ubuntu packages. I could use some instructions on how 
to get the dependencies installed with these alternative versions 
however, because I have the "python-numpy" package installed but when I 
run "python3.5 setup.py" I get ModuleNotFoundError: No module named 'numpy'

**Comment by crowlogic** [comment]
Running "python3.5 setup.py build install" worked after installing the python3-cxx-dev, libcereal-dev, swig , python3-scipy and python3-numpy

**Comment by Mbompr** [comment]
Glad to know you've managed to make it work. We're working on an easier setup script for a near future.
